module.exports = {
  important: true,
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
      mainBg: "#F4F6FC",
      transparent: "transparent",
      current: "currentColor",
      white: "#E9EDF7",
      white2: "#FFFFFF",
      borderColor: "#E9F5FC",
      iconColor: "#5D888F",
      hoverBg: "#C0C6D4",
      primary: "#0d5c75",
      info: "#A5D1E1",
      default: "#199FB1",
      txtDark: "#262626",
      txtWhite: "#eaeaea",
      Error: "#BB120E",
      Success: "#0B9314",
      Warning: "#EE6619",
      bgInput: "#EBEDED",
      background2: "#D9E0F0",
      text2: "#ABABAB",
      linkBlue:'#3E8BFF',
      gold: "#FFB300",
      silver: "#B5B7BB",
      normal: "#38CBD9",
      goldLite: '#FFF9EB',
      silverLite: '#F5F5F5',
      normalLite: '#EAFDFF',
      PureWhite: "#fff",
      greenLoad: '#36d7b7',
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      fontFamily: {
        sans: ["IRANSans", "Tahoma", "sans"],
      },
    },
  },
  plugins: [require("tailwindcss-dir")(), require("tailwindcss-rtl")],
};
