export const Districts = [
  { name: "Azarshahr", title: "آذرشهر", parent: 41, code: 1 },
  { name: "Teymurlu", title: "تیمورلو", parent: 41, code: 2 },
  { name: "Gugan", title: "گوگان", parent: 41, code: 3 },
  { name: "Mamqan", title: "ممقان", parent: 41, code: 4 },
  { name: "Osku", title: "اسکو", parent: 41, code: 5 },
  { name: "Ilkhchi", title: "ایلخچی", parent: 41, code: 6 },
  { name: "Sahand", title: "سهند", parent: 41, code: 7 },
  { name: "Ahar", title: "اهر", parent: 41, code: 8 },
  { name: "Hurand", title: "هوراند", parent: 41, code: 9 },
  { name: "Bostanabad", title: "بستان آباد", parent: 41, code: 10 },
  { name: "TekmehDash", title: "تیکمه داش", parent: 41, code: 11 },
  { name: "Bonab", title: "بناب", parent: 41, code: 12 },
  { name: "Basmenj", title: "باسمنج", parent: 41, code: 13 },
  { name: "Tabriz", title: "تبریز", parent: 41, code: 14 },
  { name: "Khosrowshah", title: "خسروشاه", parent: 41, code: 15 },
  { name: "Sardrud", title: "سردرود", parent: 41, code: 16 },
  { name: "Jolfa", title: "جلفا", parent: 41, code: 17 },
  { name: "SiahRud", title: "سیه رود", parent: 41, code: 18 },
  { name: "Hadishahr", title: "هادیشهر", parent: 41, code: 19 },
  { name: "QarahAghaj", title: "قره آغاج", parent: 41, code: 20 },
  { name: "Khomarlu", title: "خمارلو", parent: 41, code: 21 },
  { name: "Duzduzan", title: "دوزدوزان", parent: 41, code: 22 },
  { name: "Sarab", title: "سراب", parent: 41, code: 23 },
  { name: "Sharabian", title: "شربیان", parent: 41, code: 24 },
  { name: "Mehraban", title: "مهربان", parent: 41, code: 25 },
  { name: "Tasuj", title: "تسوج", parent: 41, code: 26 },
  { name: "Khamaneh", title: "خامنه", parent: 41, code: 27 },
  { name: "Sis", title: "سیس", parent: 41, code: 28 },
  { name: "Shabestar", title: "شبستر", parent: 41, code: 29 },
  { name: "Sharafkhaneh", title: "شرفخانه", parent: 41, code: 30 },
  { name: "Shendabad", title: "شندآباد", parent: 41, code: 31 },
  { name: "Sufian", title: "صوفیان", parent: 41, code: 32 },
  { name: "KuzehKanan", title: "کوزه کنان", parent: 41, code: 33 },
  { name: "Vayqan", title: "وایقان", parent: 41, code: 34 },
  { name: "JavanQala", title: "جوان قلعه", parent: 41, code: 35 },
  { name: "AjabShir", title: "عجب شیر", parent: 41, code: 36 },
  { name: "Abeshahmad", title: "آبش احمد", parent: 41, code: 37 },
  { name: "Kaleybar", title: "کلیبر", parent: 41, code: 38 },
  { name: "Kharajoo", title: "خراجو", parent: 41, code: 39 },
  { name: "Maragheh", title: "مراغه", parent: 41, code: 40 },
  { name: "BenabeMarand", title: "بناب مرند", parent: 41, code: 41 },
  { name: "Zonouz", title: "زنوز", parent: 41, code: 42 },
  { name: "Koshksaray", title: "کشکسرای", parent: 41, code: 43 },
  { name: "Marand", title: "مرند", parent: 41, code: 44 },
  { name: "Yamchi", title: "یامچی", parent: 41, code: 45 },
  { name: "Leylan", title: "لیلان", parent: 41, code: 46 },
  { name: "MobarakShahr", title: "مبارک شهر", parent: 41, code: 47 },
  { name: "Malekan", title: "ملکان", parent: 41, code: 48 },
  { name: "Aqkand", title: "آقکند", parent: 41, code: 49 },
  { name: "Achachi", title: "اچاچی", parent: 41, code: 50 },
  { name: "Tark", title: "ترک", parent: 41, code: 51 },
  { name: "Torkamanchay", title: "ترکمانچای", parent: 41, code: 52 },
  { name: "Mianeh", title: "میانه", parent: 41, code: 53 },
  { name: "Kharvana", title: "خاروانا", parent: 41, code: 54 },
  { name: "Varzaqan", title: "ورزقان", parent: 41, code: 55 },
  { name: "Bakhshayesh", title: "بخشایش", parent: 41, code: 56 },
  { name: "Khajeh", title: "خواجه", parent: 41, code: 57 },
  { name: "Zarnaq", title: "زرنق", parent: 41, code: 58 },
  { name: "Kelvanaq", title: "کلوانق", parent: 41, code: 59 },
  { name: "Heris", title: "هریس", parent: 41, code: 60 },
  { name: "Nazarkahrizi", title: "نظرکهریزی", parent: 41, code: 61 },
  { name: "Hashtrud", title: "هشترود", parent: 41, code: 62 },
  { name: "Urmia", title: "ارومیه", parent: 44, code: 63 },
  { name: "Serow", title: "سرو", parent: 44, code: 64 },
  { name: "Silvaneh", title: "سیلوانه", parent: 44, code: 65 },
  { name: "Qushchi", title: "قوشچی", parent: 44, code: 66 },
  { name: "Nushin", title: "نوشین", parent: 44, code: 67 },
  { name: "Oshnavieh", title: "اشنویه", parent: 44, code: 68 },
  { name: "Nalus", title: "نالوس", parent: 44, code: 69 },
  { name: "Bukan", title: "بوکان", parent: 44, code: 70 },
  { name: "Simmineh", title: "سیمینه", parent: 44, code: 71 },
  { name: "Poldasht", title: "پلدشت", parent: 44, code: 72 },
  { name: "NazokeOlya", title: "نازک علیا", parent: 44, code: 73 },
  { name: "Piranshahr", title: "پیرانشهر", parent: 44, code: 74 },
  { name: "GerdKashaneh", title: "گردکشانه", parent: 44, code: 75 },
  { name: "Takab", title: "تکاب", parent: 44, code: 76 },
  { name: "Avajiq", title: "آواجیق", parent: 44, code: 77 },
  { name: "SiahCheshmeh", title: "سیه چشمه", parent: 44, code: 78 },
  { name: "QarahZiaodDin", title: "قره ضیاء الدین", parent: 44, code: 79 },
  { name: "Ivaowghli", title: "ایواوغلی", parent: 44, code: 80 },
  { name: "Khoy", title: "خوی", parent: 44, code: 81 },
  { name: "DizajDiz", title: "دیزج دیز", parent: 44, code: 82 },
  { name: "Zarabad", title: "زرآباد", parent: 44, code: 83 },
  { name: "Firuraq", title: "فیرورق", parent: 44, code: 84 },
  { name: "Qatur", title: "قطور", parent: 44, code: 85 },
  { name: "Rabt", title: "ربط", parent: 44, code: 86 },
  { name: "Sardashte", title: "سردشت", parent: 44, code: 87 },
  { name: "Mirabad", title: "میرآباد", parent: 44, code: 88 },
  { name: "TazehShahr", title: "تازه شهر", parent: 44, code: 89 },
  { name: "Salmas", title: "سلماس", parent: 44, code: 90 },
  { name: "ShahinDezh", title: "شاهین دژ", parent: 44, code: 91 },
  { name: "Keshavarz", title: "کشاورز", parent: 44, code: 92 },
  { name: "Mahmudabad", title: "محمودآباد", parent: 44, code: 93 },
  { name: "Showt", title: "شوط", parent: 44, code: 94 },
  { name: "Marganlar", title: "مرگنلر", parent: 44, code: 95 },
  { name: "Bazargan", title: "بازرگان", parent: 44, code: 96 },
  { name: "Maku", title: "ماکو", parent: 44, code: 97 },
  { name: "Khalifan", title: "خلیفان", parent: 44, code: 98 },
  { name: "Mahabad", title: "مهاباد", parent: 44, code: 99 },
  { name: "Baruq", title: "باروق", parent: 44, code: 100 },
  { name: "ChaharBorj", title: "چهاربرج", parent: 44, code: 101 },
  { name: "Miandoab", title: "میاندوآب", parent: 44, code: 102 },
  { name: "Mohammadyar", title: "محمدیار", parent: 44, code: 103 },
  { name: "Naqadeh", title: "نقده", parent: 44, code: 104 },
  { name: "Ardabil", title: "اردبیل", parent: 45, code: 105 },
  { name: "Hir", title: "هیر", parent: 45, code: 106 },
  { name: "BilehSavar", title: "بیله سوار", parent: 45, code: 107 },
  { name: "Jafarabad", title: "جعفرآباد", parent: 45, code: 108 },
  { name: "Eslamabad", title: "اسلام اباد", parent: 45, code: 109 },
  { name: "AslanDuz", title: "اصلاندوز", parent: 45, code: 110 },
  { name: "Parsabad", title: "پارس آباد", parent: 45, code: 111 },
  { name: "TazehKand", title: "تازه کند", parent: 45, code: 112 },
  { name: "Khalkhal", title: "خلخال", parent: 45, code: 113 },
  { name: "Kolur", title: "کلور", parent: 45, code: 114 },
  { name: "Hashatjin", title: "هشتجین", parent: 45, code: 115 },
  { name: "Sareyn", title: "سرعین", parent: 45, code: 116 },
  { name: "Givi", title: "گیوی", parent: 45, code: 117 },
  { name: "TazehKandeAngut", title: "تازه کندانگوت", parent: 45, code: 118 },
  { name: "Germi", title: "گرمی", parent: 45, code: 119 },
  { name: "Rizi", title: "رضی", parent: 45, code: 120 },
  { name: "Fakhrabad", title: "فخراباد", parent: 45, code: 121 },
  { name: "Qosabeh", title: "قصابه", parent: 45, code: 122 },
  { name: "Lahrud", title: "لاهرود", parent: 45, code: 123 },
  { name: "Moradlu", title: "مرادلو", parent: 45, code: 124 },
  { name: "Meshginshahr", title: "مشگین شهر", parent: 45, code: 125 },
  { name: "AbiBeyglu", title: "آبی بیگلو", parent: 45, code: 126 },
  { name: "Anbaran", title: "عنبران", parent: 45, code: 127 },
  { name: "Namin", title: "نمین", parent: 45, code: 128 },
  { name: "Kuraim", title: "کوراییم", parent: 45, code: 129 },
  { name: "Nir", title: "نیر", parent: 45, code: 130 },
  { name: "AranvaBidgol", title: "آران و بیدگل", parent: 31, code: 131 },
  { name: "Abuzeydabad", title: "ابوزیدآباد", parent: 31, code: 132 },
  { name: "Sefidshahr", title: "سفیدشهر", parent: 31, code: 133 },
  { name: "Nushabad", title: "نوش آباد", parent: 31, code: 134 },
  { name: "Ardestan", title: "اردستان", parent: 31, code: 135 },
  { name: "IstgaheZavareh", title: "زواره", parent: 31, code: 136 },
  { name: "Mahabade", title: "مهاباد", parent: 31, code: 137 },
  { name: "Ezhiyeh", title: "اژیه", parent: 31, code: 138 },
  { name: "Isfahan", title: "اصفهان", parent: 31, code: 139 },
  { name: "Baharestan", title: "بهارستان", parent: 31, code: 140 },
  { name: "Tudeshk", title: "تودشک", parent: 31, code: 141 },
  { name: "Hasanabad", title: "حسن اباد", parent: 31, code: 142 },
  { name: "Ziar", title: "زیار", parent: 31, code: 143 },
  { name: "Sejzi", title: "سجزی", parent: 31, code: 144 },
  { name: "Qahjavarestan", title: "قهجاورستان", parent: 31, code: 145 },
  { name: "Kuhpayeh", title: "کوهپایه", parent: 31, code: 146 },
  { name: "Mohamadabad", title: "محمدآباد", parent: 31, code: 147 },
  { name: "Nasrabad", title: "نصرآباد", parent: 31, code: 148 },
  { name: "Nikabad", title: "نیک آباد", parent: 31, code: 149 },
  { name: "Varzaneh", title: "ورزنه", parent: 31, code: 150 },
  { name: "Harand", title: "هرند", parent: 31, code: 151 },
  { name: "Habibabad", title: "حبیب آباد", parent: 31, code: 152 },
  { name: "Khowrzuq", title: "خورزوق", parent: 31, code: 153 },
  { name: "Dastgerd", title: "دستگرد", parent: 31, code: 154 },
  { name: "Dowlatabad", title: "دولت آباد", parent: 31, code: 155 },
  { name: "Sin", title: "سین", parent: 31, code: 156 },
  { name: "ShapurAbad", title: "شاپورآباد", parent: 31, code: 157 },
  { name: "Komeshcheh", title: "کمشچه", parent: 31, code: 158 },
  { name: "Afus", title: "افوس", parent: 31, code: 159 },
  { name: "BuinvaMiandasht", title: "بویین ومیاندشت", parent: 31, code: 160 },
  { name: "Tiran", title: "تیران", parent: 31, code: 161 },
  { name: "Rezvanshahr", title: "رضوانشهر", parent: 31, code: 162 },
  { name: "Asgaran", title: "عسگران", parent: 31, code: 163 },
  { name: "Chadegan", title: "چادگان", parent: 31, code: 164 },
  { name: "Rozveh", title: "رزوه", parent: 31, code: 165 },
  { name: "Asgharabad", title: "اصغرآباد", parent: 31, code: 166 },
  { name: "KhomeyniShahr", title: "خمینی شهر", parent: 31, code: 167 },
  { name: "DarrehChah", title: "درچه", parent: 31, code: 168 },
  { name: "Kushk", title: "کوشک", parent: 31, code: 169 },
  { name: "Khansar", title: "خوانسار", parent: 31, code: 170 },
  { name: "Jandaq", title: "جندق", parent: 31, code: 171 },
  { name: "Khur", title: "خور", parent: 31, code: 172 },
  { name: "Farrokhi", title: "فرخی", parent: 31, code: 173 },
  { name: "Dehaqan", title: "دهاقان", parent: 31, code: 174 },
  { name: "Golshan", title: "گلشن", parent: 31, code: 175 },
  { name: "Hanna", title: "حنا", parent: 31, code: 176 },
  { name: "Semirom", title: "سمیرم", parent: 31, code: 177 },
  { name: "Komeh", title: "کمه", parent: 31, code: 178 },
  { name: "Vanak", title: "ونک", parent: 31, code: 179 },
  { name: "ShahinShahr", title: "شاهین شهر", parent: 31, code: 180 },
  { name: "Gorgab", title: "گرگاب", parent: 31, code: 181 },
  { name: "Gazborkhar", title: "گزبرخوار", parent: 31, code: 182 },
  { name: "LayBid", title: "لای بید", parent: 31, code: 183 },
  { name: "Meymeh", title: "میمه", parent: 31, code: 184 },
  { name: "Vazvan", title: "وزوان", parent: 31, code: 185 },
  { name: "Shahreza", title: "شهرضا", parent: 31, code: 186 },
  { name: "Manzariyeh", title: "منظریه", parent: 31, code: 187 },
  { name: "Daran", title: "داران", parent: 31, code: 188 },
  { name: "Damaneh", title: "دامنه", parent: 31, code: 189 },
  { name: "BarfAnbar", title: "برف انبار", parent: 31, code: 190 },
  { name: "Fereydunshahr", title: "فریدونشهر", parent: 31, code: 191 },
  { name: "Abrisham", title: "ابریشم", parent: 31, code: 192 },
  { name: "Imanshahr", title: "ایمانشهر", parent: 31, code: 193 },
  { name: "BaharanShahr", title: "بهاران شهر", parent: 31, code: 194 },
  { name: "PirBakran", title: "پیربکران", parent: 31, code: 195 },
  { name: "Zazeran", title: "زازران", parent: 31, code: 196 },
  { name: "Falavarjan", title: "فلاورجان", parent: 31, code: 197 },
  { name: "Qahderijan", title: "قهدریجان", parent: 31, code: 198 },
  {
    name: "KelishadvaSudarjan",
    title: "کلیشاد و سودرجان",
    parent: 31,
    code: 199,
  },
  { name: "Barzok", title: "برزک", parent: 31, code: 200 },
  { name: "JowsheqaneQali", title: "جوشقان قالی", parent: 31, code: 201 },
  { name: "Qamsar", title: "قمصر", parent: 31, code: 202 },
  { name: "Kashan", title: "کاشان", parent: 31, code: 203 },
  { name: "KamuvaChugan", title: "کامو و چوگان", parent: 31, code: 204 },
  { name: "Meshkat", title: "مشکات", parent: 31, code: 205 },
  { name: "Neyasar", title: "نیاسر", parent: 31, code: 206 },
  { name: "Golpayegan", title: "گلپایگان", parent: 31, code: 207 },
  { name: "Golshahr", title: "گلشهر", parent: 31, code: 208 },
  { name: "Guged", title: "گوگد", parent: 31, code: 209 },
  { name: "BagheBahadoran", title: "باغ بهادران", parent: 31, code: 210 },
  { name: "Baghshad", title: "باغشاد", parent: 31, code: 211 },
  { name: "Chermahin", title: "چرمهین", parent: 31, code: 212 },
  { name: "Chamgardan", title: "چمگردان", parent: 31, code: 213 },
  { name: "ZayandehRud", title: "زاینده رود", parent: 31, code: 214 },
  { name: "ZarrinShahr", title: "زرین شهر", parent: 31, code: 215 },
  { name: "SedehLenjan", title: "سده لنجان", parent: 31, code: 216 },
  { name: "Fuladshahr", title: "فولادشهر", parent: 31, code: 217 },
  { name: "Varnamkhvast", title: "ورنامخواست", parent: 31, code: 218 },
  { name: "Dizicheh", title: "دیزیچه", parent: 31, code: 219 },
  { name: "Zibashahr", title: "زیباشهر", parent: 31, code: 220 },
  { name: "Talkhvoncheh", title: "طالخونچه", parent: 31, code: 221 },
  { name: "Karkevand", title: "کرکوند", parent: 31, code: 222 },
  { name: "Mobarakeh", title: "مبارکه", parent: 31, code: 223 },
  { name: "Majlesi", title: "مجلسی", parent: 31, code: 224 },
  { name: "Anarak", title: "انارک", parent: 31, code: 225 },
  { name: "Bafran", title: "بافران", parent: 31, code: 226 },
  { name: "Nain", title: "نایین", parent: 31, code: 227 },
  { name: "Jowzdan", title: "جوزدان", parent: 31, code: 228 },
  { name: "Dehaq", title: "دهق", parent: 31, code: 229 },
  { name: "Alavijeh", title: "علویجه", parent: 31, code: 230 },
  { name: "Kahrizsang", title: "کهریزسنگ", parent: 31, code: 231 },
  { name: "Goldasht", title: "گلدشت", parent: 31, code: 232 },
  { name: "Najafabad", title: "نجف آباد", parent: 31, code: 233 },
  { name: "Badrud", title: "بادرود", parent: 31, code: 234 },
  { name: "Khaledabad", title: "خالدآباد", parent: 31, code: 235 },
  { name: "TarqRud", title: "طرق رود", parent: 31, code: 236 },
  { name: "Natanz", title: "نطنز", parent: 31, code: 237 },
  { name: "Eshtehard", title: "اشتهارد", parent: 26, code: 238 },
  { name: "Chaharbagh", title: "چهارباغ", parent: 26, code: 239 },
  {
    name: "ShahreJadideHashtgerd",
    title: "شهر جدید هشتگرد",
    parent: 26,
    code: 240,
  },
  { name: "Kuhsar", title: "کوهسار", parent: 26, code: 241 },
  { name: "Golsar", title: "گلسار", parent: 26, code: 242 },
  { name: "Hashtgerd", title: "هشتگرد", parent: 26, code: 243 },
  { name: "Taleqan", title: "طالقان", parent: 26, code: 244 },
  { name: "Fardis", title: "فردیس", parent: 26, code: 245 },
  { name: "MeshkinDasht", title: "مشکین دشت", parent: 26, code: 246 },
  { name: "Asara", title: "آسارا", parent: 26, code: 247 },
  { name: "Karaj", title: "کرج", parent: 26, code: 248 },
  { name: "KamalShahr", title: "کمال شهر", parent: 26, code: 249 },
  { name: "Garmdareh", title: "گرمدره", parent: 26, code: 250 },
  { name: "Mahdasht", title: "ماهدشت", parent: 26, code: 251 },
  { name: "Mohammadshahr", title: "محمدشهر", parent: 26, code: 252 },
  { name: "Tankaman", title: "تنکمان", parent: 26, code: 253 },
  { name: "Nazarabad", title: "نظرآباد", parent: 26, code: 254 },
  { name: "Abdanan", title: "آبدانان", parent: 84, code: 255 },
  { name: "SarabBagh", title: "سراب باغ", parent: 84, code: 256 },
  { name: "Murmuri", title: "مورموری", parent: 84, code: 257 },
  { name: "Ilam", title: "ایلام", parent: 84, code: 258 },
  { name: "Chavar", title: "چوار", parent: 84, code: 259 },
  { name: "Eyvan", title: "ایوان", parent: 84, code: 260 },
  { name: "Zarneh", title: "زرنه", parent: 84, code: 261 },
  { name: "Badreh", title: "بدره", parent: 84, code: 262 },
  { name: "Asemanabad", title: "آسمان آباد", parent: 84, code: 263 },
  { name: "Belavah", title: "بلاوه", parent: 84, code: 264 },
  { name: "Towhid", title: "توحید", parent: 84, code: 265 },
  { name: "Sarableh", title: "سرابله", parent: 84, code: 266 },
  { name: "Shabab", title: "شباب", parent: 84, code: 267 },
  { name: "DarrehShahr", title: "دره شهر", parent: 84, code: 268 },
  { name: "Mazhin", title: "ماژین", parent: 84, code: 269 },
  { name: "Pahleh", title: "پهله", parent: 84, code: 270 },
  { name: "Dehloran", title: "دهلران", parent: 84, code: 271 },
  { name: "Musian", title: "موسیان", parent: 84, code: 272 },
  { name: "Meymehe", title: "میمه", parent: 84, code: 273 },
  { name: "Lumar", title: "لومار", parent: 84, code: 274 },
  { name: "Arkavaz", title: "ارکواز", parent: 84, code: 275 },
  { name: "Delgosha", title: "دلگشا", parent: 84, code: 276 },
  { name: "Mohr", title: "مهر", parent: 84, code: 277 },
  { name: "Salehabad", title: "صالح آباد", parent: 84, code: 278 },
  { name: "Mehran", title: "مهران", parent: 84, code: 279 },
  { name: "Bushehr", title: "بوشهر", parent: 77, code: 280 },
  { name: "Choghadak", title: "چغادک", parent: 77, code: 281 },
  { name: "Kharg", title: "خارک", parent: 77, code: 282 },
  { name: "Alishahr", title: "عالی شهر", parent: 77, code: 283 },
  { name: "Abad", title: "آباد", parent: 77, code: 284 },
  { name: "Ahram", title: "اهرم", parent: 77, code: 285 },
  { name: "Delvar", title: "دلوار", parent: 77, code: 286 },
  { name: "Anarestan", title: "انارستان", parent: 77, code: 287 },
  { name: "Jam", title: "جم", parent: 77, code: 288 },
  { name: "Riz", title: "ریز", parent: 77, code: 289 },
  { name: "AbPakhsh", title: "آب پخش", parent: 77, code: 290 },
  { name: "Borazjan", title: "برازجان", parent: 77, code: 291 },
  { name: "Bushkan", title: "بوشکان", parent: 77, code: 292 },
  { name: "TangeEram", title: "تنگ ارم", parent: 77, code: 293 },
  { name: "Dalaki", title: "دالکی", parent: 77, code: 294 },
  { name: "Sadabad", title: "سعد آباد", parent: 77, code: 295 },
  { name: "Shabankareh", title: "شبانکاره", parent: 77, code: 296 },
  { name: "Kalameh", title: "کلمه", parent: 77, code: 297 },
  { name: "Vahdatiyeh", title: "وحدتیه", parent: 77, code: 298 },
  { name: "Baduleh", title: "بادوله", parent: 77, code: 299 },
  { name: "Khormoj", title: "خورموج", parent: 77, code: 300 },
  { name: "Shanbeh", title: "شنبه", parent: 77, code: 301 },
  { name: "Kaki", title: "کاکی", parent: 77, code: 302 },
  { name: "Abdan", title: "آبدان", parent: 77, code: 303 },
  { name: "BordKhun", title: "بردخون", parent: 77, code: 304 },
  { name: "Bardestan", title: "بردستان", parent: 77, code: 305 },
  { name: "BandareDeyr", title: "بندردیر", parent: 77, code: 306 },
  { name: "Dorahak", title: "دوراهک", parent: 77, code: 307 },
  { name: "ImamHassan", title: "امام حسن", parent: 77, code: 308 },
  { name: "BandarDeylam", title: "بندردیلم", parent: 77, code: 309 },
  { name: "Asaluyeh", title: "عسلویه", parent: 77, code: 310 },
  { name: "NakhlTaqi", title: "نخل تقی", parent: 77, code: 311 },
  { name: "BandareKangan", title: "بندرکنگان", parent: 77, code: 312 },
  { name: "Bank", title: "بنک", parent: 77, code: 313 },
  { name: "Siraf", title: "سیراف", parent: 77, code: 314 },
  { name: "BandarRig", title: "بندرریگ", parent: 77, code: 315 },
  { name: "BandarGanaveh", title: "بندرگناوه", parent: 77, code: 316 },
  {
    name: "AhmadabadeMostowfi",
    title: "احمد آباد مستوفی",
    parent: 21,
    code: 317,
  },
  { name: "Eslamshahr", title: "اسلامشهر", parent: 21, code: 318 },
  { name: "Chahardangeh", title: "چهاردانگه", parent: 21, code: 319 },
  { name: "Salehieh", title: "صالحیه", parent: 21, code: 320 },
  { name: "Golestan", title: "گلستان", parent: 21, code: 321 },
  { name: "NasimShahr", title: "نسیم شهر", parent: 21, code: 322 },
  { name: "Pakdasht", title: "پاکدشت", parent: 21, code: 323 },
  { name: "Sharifabad", title: "شریف آباد", parent: 21, code: 324 },
  { name: "Ferunabad", title: "فرون آباد", parent: 21, code: 325 },
  { name: "Bumehen", title: "بومهن", parent: 21, code: 326 },
  { name: "Pardis", title: "پردیس", parent: 21, code: 327 },
  { name: "Pishva", title: "پیشوا", parent: 21, code: 328 },
  { name: "Tehran", title: "تهران", parent: 21, code: 329 },
  { name: "Absard", title: "آبسرد", parent: 21, code: 330 },
  { name: "Abali", title: "آبعلی", parent: 21, code: 331 },
  { name: "Damavand", title: "دماوند", parent: 21, code: 332 },
  { name: "Rudehen", title: "رودهن", parent: 21, code: 333 },
  { name: "Kilan", title: "کیلان", parent: 21, code: 334 },
  { name: "Parand", title: "پرند", parent: 21, code: 335 },
  { name: "RobatKarim", title: "رباط کریم", parent: 21, code: 336 },
  { name: "Nasirshahr", title: "نصیرشهر", parent: 21, code: 337 },
  { name: "Baqershahr", title: "باقرشهر", parent: 21, code: 338 },
  { name: "Hasanabade", title: "حسن آباد", parent: 21, code: 339 },
  { name: "ShahreRey", title: "ری", parent: 21, code: 340 },
  { name: "Kahrizak", title: "کهریزک", parent: 21, code: 341 },
  { name: "Tajrish", title: "تجریش", parent: 21, code: 342 },
  { name: "Shemshak", title: "شمشک", parent: 21, code: 343 },
  { name: "Fasham", title: "فشم", parent: 21, code: 344 },
  { name: "Lavasan", title: "لواسان", parent: 21, code: 345 },
  { name: "Andisheh", title: "اندیشه", parent: 21, code: 346 },
  { name: "Baghestan", title: "باغستان", parent: 21, code: 347 },
  { name: "Shahedshahr", title: "شاهدشهر", parent: 21, code: 348 },
  { name: "Shahriar", title: "شهریار", parent: 21, code: 349 },
  { name: "Sabashahr", title: "صباشهر", parent: 21, code: 350 },
  { name: "Ferdowsieh", title: "فردوسیه", parent: 21, code: 351 },
  { name: "Vahidieh", title: "وحیدیه", parent: 21, code: 352 },
  { name: "Arjomand", title: "ارجمند", parent: 21, code: 353 },
  { name: "Firuzkuh", title: "فیروزکوه", parent: 21, code: 354 },
  { name: "Qods", title: "قدس", parent: 21, code: 355 },
  { name: "Qarchak", title: "قرچک", parent: 21, code: 356 },
  { name: "Safadasht", title: "صفادشت", parent: 21, code: 357 },
  { name: "Malard", title: "ملارد", parent: 21, code: 358 },
  { name: "Javadabad", title: "جوادآباد", parent: 21, code: 359 },
  { name: "Varamin", title: "ورامین", parent: 21, code: 360 },
  { name: "Ardal", title: "اردل", parent: 38, code: 361 },
  { name: "Dashtak", title: "دشتک", parent: 38, code: 362 },
  { name: "Sorkhun", title: "سرخون", parent: 38, code: 363 },
  { name: "Kaj", title: "کاج", parent: 38, code: 364 },
  { name: "Borujen", title: "بروجن", parent: 38, code: 365 },
  { name: "Boldaji", title: "بلداجی", parent: 38, code: 366 },
  { name: "Sefiddasht", title: "سفیددشت", parent: 38, code: 367 },
  { name: "Faradonbeh", title: "فرادبنه", parent: 38, code: 368 },
  { name: "Gandoman", title: "گندمان", parent: 38, code: 369 },
  { name: "Naqneh", title: "نقنه", parent: 38, code: 370 },
  { name: "Ben", title: "بن", parent: 38, code: 371 },
  { name: "Vardanjan", title: "وردنجان", parent: 38, code: 372 },
  { name: "Saman", title: "سامان", parent: 38, code: 373 },
  { name: "Sudjan", title: "سودجان", parent: 38, code: 374 },
  { name: "Sureshjan", title: "سورشجان", parent: 38, code: 375 },
  { name: "ShahreKord", title: "شهرکرد", parent: 38, code: 376 },
  { name: "Taqanak", title: "طاقانک", parent: 38, code: 377 },
  { name: "FarrokhShahr", title: "فرخ شهر", parent: 38, code: 378 },
  { name: "Kian", title: "کیان", parent: 38, code: 379 },
  { name: "Nafech", title: "نافچ", parent: 38, code: 380 },
  { name: "Haruni", title: "هارونی", parent: 38, code: 381 },
  { name: "Hafshejan", title: "هفشجان", parent: 38, code: 382 },
  { name: "Babaheydar", title: "باباحیدر", parent: 38, code: 383 },
  { name: "Pardanjan", title: "پردنجان", parent: 38, code: 384 },
  { name: "Junqan", title: "جونقان", parent: 38, code: 385 },
  { name: "Cholicheh", title: "چلیچه", parent: 38, code: 386 },
  { name: "Farsan", title: "فارسان", parent: 38, code: 387 },
  { name: "Gujan", title: "گوجان", parent: 38, code: 388 },
  { name: "Bazoft", title: "بازفت", parent: 38, code: 389 },
  { name: "Chelgard", title: "چلگرد", parent: 38, code: 390 },
  { name: "Samsami", title: "صمصامی", parent: 38, code: 391 },
  { name: "Dastana", title: "دستنا", parent: 38, code: 392 },
  { name: "Shalamzar", title: "شلمزار", parent: 38, code: 393 },
  { name: "Gahru", title: "گهرو", parent: 38, code: 394 },
  { name: "Naghan", title: "ناغان", parent: 38, code: 395 },
  { name: "Aluni", title: "آلونی", parent: 38, code: 396 },
  { name: "Sardaashte", title: "سردشت", parent: 38, code: 397 },
  { name: "Lordegan", title: "لردگان", parent: 38, code: 398 },
  { name: "MaleKhalifeh", title: "مال خلیفه", parent: 38, code: 399 },
  { name: "Monj", title: "منج", parent: 38, code: 400 },
  { name: "Eresk", title: "ارسک", parent: 56, code: 401 },
  { name: "Boshruyeh", title: "بشرویه", parent: 56, code: 402 },
  { name: "Birjand", title: "بیرجند", parent: 56, code: 403 },
  { name: "Khusf", title: "خوسف", parent: 56, code: 404 },
  { name: "Mohammadshahre", title: "محمدشهر", parent: 56, code: 405 },
  { name: "Asadiyeh", title: "اسدیه", parent: 56, code: 406 },
  { name: "TabaseMasina", title: "طبس مسینا", parent: 56, code: 407 },
  { name: "Qohestan", title: "قهستان", parent: 56, code: 408 },
  { name: "Gazik", title: "گزیک", parent: 56, code: 409 },
  { name: "Hajjiabad", title: "حاجی آباد", parent: 56, code: 410 },
  { name: "Dehkadeh", title: "زهان", parent: 56, code: 411 },
  { name: "Ayask", title: "آیسک", parent: 56, code: 412 },
  { name: "Sarayan", title: "سرایان", parent: 56, code: 413 },
  { name: "SehQaleh", title: "سه قلعه", parent: 56, code: 414 },
  { name: "Sarbisheh", title: "سربیشه", parent: 56, code: 415 },
  { name: "Mud", title: "مود", parent: 56, code: 416 },
  { name: "Deyhuk", title: "دیهوک", parent: 56, code: 417 },
  { name: "Tabas", title: "طبس", parent: 56, code: 418 },
  { name: "Eshqabad", title: "عشق آباد", parent: 56, code: 419 },
  { name: "Eslamiyeh", title: "اسلامیه", parent: 56, code: 420 },
  { name: "Ferdows", title: "فردوس", parent: 56, code: 421 },
  { name: "ArianShahr", title: "آرین شهر", parent: 56, code: 422 },
  { name: "Esfeden", title: "اسفدن", parent: 56, code: 423 },
  { name: "KhezriDashtebayaz", title: "خضری دشت بیاض", parent: 56, code: 424 },
  { name: "Qaen", title: "قاین", parent: 56, code: 425 },
  { name: "Nimbeluk", title: "نیمبلوک", parent: 56, code: 426 },
  { name: "Shusef", title: "شوسف", parent: 56, code: 427 },
  { name: "Nehbandan", title: "نهبندان", parent: 56, code: 428 },
  { name: "Bakharz", title: "باخرز", parent: 51, code: 429 },
  { name: "Bajestan", title: "بجستان", parent: 51, code: 430 },
  { name: "Yunesi", title: "یونسی", parent: 51, code: 431 },
  { name: "Anabad", title: "انابد", parent: 51, code: 432 },
  { name: "Bardaskan", title: "بردسکن", parent: 51, code: 433 },
  { name: "Shahrabad", title: "شهراباد", parent: 51, code: 434 },
  { name: "Shandiz", title: "شاندیز", parent: 51, code: 435 },
  { name: "Torqabeh", title: "طرقبه", parent: 51, code: 436 },
  { name: "Taybad", title: "تایباد", parent: 51, code: 437 },
  { name: "Kariz", title: "کاریز", parent: 51, code: 438 },
  { name: "Mashhade", title: "مشهدریزه", parent: 51, code: 439 },
  { name: "Ahmadabad", title: "احمدابادصولت", parent: 51, code: 440 },
  { name: "TorbateJam", title: "تربت جام", parent: 51, code: 441 },
  { name: "Salehabade", title: "صالح آباد", parent: 51, code: 442 },
  { name: "Nasrabade", title: "نصرآباد", parent: 51, code: 443 },
  { name: "NilShahr", title: "نیل شهر", parent: 51, code: 444 },
  { name: "Bayg", title: "بایک", parent: 51, code: 445 },
  { name: "TorbateHeydarieh", title: "تربت حیدریه", parent: 51, code: 446 },
  { name: "RobateSang", title: "رباط سنگ", parent: 51, code: 447 },
  { name: "Kadkan", title: "کدکن", parent: 51, code: 448 },
  { name: "Joghtay", title: "جغتای", parent: 51, code: 449 },
  { name: "Neqab", title: "نقاب", parent: 51, code: 450 },
  { name: "Chenaran", title: "چناران", parent: 51, code: 451 },
  { name: "Golbahar", title: "گلبهار", parent: 51, code: 452 },
  { name: "Golmakan", title: "گلمکان", parent: 51, code: 453 },
  { name: "Khalilabad", title: "خلیل آباد", parent: 51, code: 454 },
  { name: "Kondor", title: "کندر", parent: 51, code: 455 },
  { name: "Khaf", title: "خواف", parent: 51, code: 456 },
  { name: "Salami", title: "سلامی", parent: 51, code: 457 },
  { name: "Sangan", title: "سنگان", parent: 51, code: 458 },
  { name: "Qasemabad", title: "قاسم آباد", parent: 51, code: 459 },
  { name: "Nashtifan", title: "نشتیفان", parent: 51, code: 460 },
  { name: "Soltanabad", title: "سلطان آباد", parent: 51, code: 461 },
  { name: "Davarzan", title: "داورزن", parent: 51, code: 462 },
  { name: "Chapeshlu", title: "چاپشلو", parent: 51, code: 463 },
  { name: "Dargaz", title: "درگز", parent: 51, code: 464 },
  { name: "Lotfabad", title: "لطف آباد", parent: 51, code: 465 },
  { name: "Nowkhandan", title: "نوخندان", parent: 51, code: 466 },
  { name: "Jangal", title: "جنگل", parent: 51, code: 467 },
  { name: "Roshtkhvar", title: "رشتخوار", parent: 51, code: 468 },
  { name: "Dowlatabade", title: "دولت آباد", parent: 51, code: 469 },
  { name: "RudAb", title: "روداب", parent: 51, code: 470 },
  { name: "Sabzevar", title: "سبزوار", parent: 51, code: 471 },
  { name: "Sheshtamad", title: "ششتمد", parent: 51, code: 472 },
  { name: "Sarakhs", title: "سرخس", parent: 51, code: 473 },
  { name: "Mazdavand", title: "مزدآوند", parent: 51, code: 474 },
  { name: "SefidSang", title: "سفیدسنگ", parent: 51, code: 475 },
  { name: "Farhadgerd", title: "فرهادگرد", parent: 51, code: 476 },
  { name: "Fariman", title: "فریمان", parent: 51, code: 477 },
  { name: "Qalandarabad", title: "قلندرآباد", parent: 51, code: 478 },
  { name: "Firuzeh", title: "فیروزه", parent: 51, code: 479 },
  { name: "Hemmatabad", title: "همت آباد", parent: 51, code: 480 },
  { name: "Bajgiran", title: "باجگیران", parent: 51, code: 481 },
  { name: "Quchan", title: "قوچان", parent: 51, code: 482 },
  { name: "Rivash", title: "ریوش", parent: 51, code: 483 },
  { name: "Kashmar", title: "کاشمر", parent: 51, code: 484 },
  { name: "Shahrezu", title: "شهرزو", parent: 51, code: 485 },
  { name: "Kalat", title: "کلات", parent: 51, code: 486 },
  { name: "Bidokht", title: "بیدخت", parent: 51, code: 487 },
  { name: "Kakhk", title: "کاخک", parent: 51, code: 488 },
  { name: "Gonabad", title: "گناباد", parent: 51, code: 489 },
  { name: "Razaviyeh", title: "رضویه", parent: 51, code: 490 },
  { name: "Mashhad", title: "مشهد", parent: 51, code: 491 },
  { name: "MashhadSamen", title: "مشهد ثامن", parent: 51, code: 492 },
  { name: "Malekabad", title: "ملک آباد", parent: 51, code: 493 },
  { name: "Shadmehr", title: "شادمهر", parent: 51, code: 494 },
  { name: "Feyzabad", title: "فیض آباد", parent: 51, code: 495 },
  { name: "Bar", title: "بار", parent: 51, code: 496 },
  { name: "Chakaneh", title: "چکنه", parent: 51, code: 497 },
  { name: "Kharv", title: "خرو", parent: 51, code: 498 },
  { name: "Darrud", title: "درود", parent: 51, code: 499 },
  { name: "Eshqabade", title: "عشق آباد", parent: 51, code: 500 },
  { name: "Qadamgah", title: "قدمگاه", parent: 51, code: 501 },
  { name: "Nishapur", title: "نیشابور", parent: 51, code: 502 },
  { name: "Esfarayen", title: "اسفراین", parent: 58, code: 503 },
  { name: "Safiabad", title: "صفی آباد", parent: 58, code: 504 },
  { name: "Bojnord", title: "بجنورد", parent: 58, code: 505 },
  { name: "Chenarane", title: "چناران شهر", parent: 58, code: 506 },
  { name: "HesareGarmkhan", title: "حصارگرمخان", parent: 58, code: 507 },
  { name: "Jajarm", title: "جاجرم", parent: 58, code: 508 },
  { name: "IstgaheSankhvast", title: "سنخواست", parent: 58, code: 509 },
  { name: "Showqan", title: "شوقان", parent: 58, code: 510 },
  { name: "Raz", title: "راز", parent: 58, code: 511 },
  { name: "Ziarat", title: "زیارت", parent: 58, code: 512 },
  { name: "Shirvan", title: "شیروان", parent: 58, code: 513 },
  { name: "QushKhaneh", title: "قوشخانه", parent: 58, code: 514 },
  { name: "Lujali", title: "لوجلی", parent: 58, code: 515 },
  { name: "Titkanlu", title: "تیتکانلو", parent: 58, code: 516 },
  { name: "Faruj", title: "فاروج", parent: 58, code: 517 },
  { name: "Ayur", title: "ایور", parent: 58, code: 518 },
  { name: "Daraq", title: "درق", parent: 58, code: 519 },
  { name: "Garmeh", title: "گرمه", parent: 58, code: 520 },
  { name: "Ashkhaneh", title: "آشخانه", parent: 58, code: 521 },
  { name: "Ava", title: "آوا", parent: 58, code: 522 },
  { name: "PishQaleh", title: "پیش قلعه", parent: 58, code: 523 },
  { name: "Qazi", title: "قاضی", parent: 58, code: 524 },
  { name: "Abadan", title: "آبادان", parent: 61, code: 525 },
  { name: "Arvandkenar", title: "اروندکنار", parent: 61, code: 526 },
  { name: "Chavibdeh", title: "چویبده", parent: 61, code: 527 },
  { name: "Aghajari", title: "آغاجاری", parent: 61, code: 528 },
  { name: "Omidiyeh", title: "امیدیه", parent: 61, code: 529 },
  { name: "Jayezan", title: "جایزان", parent: 61, code: 530 },
  { name: "Abozhdan", title: "آبژدان", parent: 61, code: 531 },
  { name: "QalehKhvajeh", title: "قلعه خواجه", parent: 61, code: 532 },
  { name: "Azadkhan", title: "آزادی", parent: 61, code: 533 },
  { name: "Andimeshk", title: "اندیمشک", parent: 61, code: 534 },
  { name: "Bidrubeh", title: "بیدروبه", parent: 61, code: 535 },
  { name: "ChamGolak", title: "چم گلک", parent: 61, code: 536 },
  { name: "Hoseyniyeh", title: "حسینیه", parent: 61, code: 537 },
  { name: "Elhayi", title: "الهایی", parent: 61, code: 538 },
  { name: "Ahvaz", title: "اهواز", parent: 61, code: 539 },
  { name: "Izeh", title: "ایذه", parent: 61, code: 540 },
  { name: "Dehdez", title: "دهدز", parent: 61, code: 541 },
  { name: "BagheMalek", title: "باغ ملک", parent: 61, code: 542 },
  { name: "Seydun", title: "صیدون", parent: 61, code: 543 },
  { name: "QalehTol", title: "قلعه تل", parent: 61, code: 544 },
  { name: "Meydavud", title: "میداود", parent: 61, code: 545 },
  { name: "Sheyban", title: "شیبان", parent: 61, code: 546 },
  { name: "Mollasani", title: "ملاثانی", parent: 61, code: 547 },
  { name: "Veys", title: "ویس", parent: 61, code: 548 },
  {
    name: "BandarImamKhomeini",
    title: "بندر امام خمینی",
    parent: 61,
    code: 549,
  },
  { name: "BandarMahshahr", title: "بندرماهشهر", parent: 61, code: 550 },
  { name: "Chamran", title: "چمران", parent: 61, code: 551 },
  { name: "Behbahan", title: "بهبهان", parent: 61, code: 552 },
  { name: "Tashan", title: "تشان", parent: 61, code: 553 },
  { name: "Sardasht", title: "سردشت", parent: 61, code: 554 },
  { name: "Mansuriyeh", title: "منصوریه", parent: 61, code: 555 },
  { name: "Hamidiyeh", title: "حمیدیه", parent: 61, code: 556 },
  { name: "Khorramshahr", title: "خرمشهر", parent: 61, code: 557 },
  { name: "Moqavemat", title: "مقاومت", parent: 61, code: 558 },
  { name: "Minushahr", title: "مینوشهر", parent: 61, code: 559 },
  { name: "Choghamish", title: "چغامیش", parent: 61, code: 560 },
  { name: "Hamzeh", title: "حمزه", parent: 61, code: 561 },
  { name: "Dezful", title: "دزفول", parent: 61, code: 562 },
  { name: "Saland", title: "سالند", parent: 61, code: 563 },
  { name: "SiahMansur", title: "سیاه منصور", parent: 61, code: 564 },
  { name: "Shamsabad", title: "شمس آباد", parent: 61, code: 565 },
  { name: "Dezab", title: "شهر امام", parent: 61, code: 566 },
  { name: "Safieabad", title: "صفی آباد", parent: 61, code: 567 },
  { name: "Mianrud", title: "میانرود", parent: 61, code: 568 },
  { name: "AbouHomeyzeh", title: "ابوحمیظه", parent: 61, code: 569 },
  { name: "Bostan", title: "بستان", parent: 61, code: 570 },
  { name: "Susangerd", title: "سوسنگرد", parent: 61, code: 571 },
  { name: "KuteSeyyedNaim", title: "کوت سیدنعیم", parent: 61, code: 572 },
  { name: "Ramshir", title: "رامشیر", parent: 61, code: 573 },
  { name: "Moshrageh", title: "مشراگه", parent: 61, code: 574 },
  { name: "Ramhormoz", title: "رامهرمز", parent: 61, code: 575 },
  { name: "Khanafereh", title: "خنافره", parent: 61, code: 576 },
  { name: "Darkhovin", title: "دارخوین", parent: 61, code: 577 },
  { name: "Shadegan", title: "شادگان", parent: 61, code: 578 },
  { name: "Alvan", title: "الوان", parent: 61, code: 579 },
  { name: "Horr", title: "حر", parent: 61, code: 580 },
  { name: "SeyyedShavur", title: "شاوور", parent: 61, code: 581 },
  { name: "Shush", title: "شوش", parent: 61, code: 582 },
  { name: "JariyehSeyyedKarm", title: "فتح المبین", parent: 61, code: 583 },
  { name: "Sardaran", title: "سرداران", parent: 61, code: 584 },
  { name: "Sherafat", title: "شرافت", parent: 61, code: 585 },
  { name: "Shushtar", title: "شوشتر", parent: 61, code: 586 },
  { name: "Guriyeh", title: "گوریه", parent: 61, code: 587 },
  { name: "KutAbdollah", title: "کوت عبداله", parent: 61, code: 588 },
  { name: "Torkalaki", title: "ترکالکی", parent: 61, code: 589 },
  { name: "JannatMakan", title: "جنت مکان", parent: 61, code: 590 },
  { name: "Semaleh", title: "سماله", parent: 61, code: 591 },
  { name: "SalehShahr", title: "صالح شهر", parent: 61, code: 592 },
  { name: "Gotvand", title: "گتوند", parent: 61, code: 593 },
  { name: "Lali", title: "لالی", parent: 61, code: 594 },
  { name: "Golgir", title: "گلگیر", parent: 61, code: 595 },
  { name: "MasjedSoleyman", title: "مسجد سلیمان", parent: 61, code: 596 },
  { name: "Haftkel", title: "هفتگل", parent: 61, code: 597 },
  { name: "Zahreh", title: "زهره", parent: 61, code: 598 },
  { name: "Hendijan", title: "هندیجان", parent: 61, code: 599 },
  { name: "Rafi", title: "رفیع", parent: 61, code: 600 },
  { name: "Hoveyzeh", title: "هویزه", parent: 61, code: 601 },
  { name: "Abhar", title: "ابهر", parent: 24, code: 602 },
  { name: "SainQaleh", title: "صایین قلعه", parent: 24, code: 603 },
  { name: "Hidaj", title: "هیدج", parent: 24, code: 604 },
  { name: "Halab", title: "حلب", parent: 24, code: 605 },
  { name: "Zarrinabad", title: "زرین آباد", parent: 24, code: 606 },
  { name: "ZarrinRud", title: "زرین رود", parent: 24, code: 607 },
  { name: "Sojas", title: "سجاس", parent: 24, code: 608 },
  { name: "Sohrevard", title: "سهرورد", parent: 24, code: 609 },
  { name: "Qeydar", title: "قیدار", parent: 24, code: 610 },
  { name: "Karasf", title: "کرسف", parent: 24, code: 611 },
  { name: "Garmab", title: "گرماب", parent: 24, code: 612 },
  { name: "NourAbad", title: "نوربهار", parent: 24, code: 613 },
  { name: "Khorramdarreh", title: "خرمدره", parent: 24, code: 614 },
  { name: "Armaghankhaneh", title: "ارمغانخانه", parent: 24, code: 615 },
  { name: "Zanjan", title: "زنجان", parent: 24, code: 616 },
  { name: "NikPey", title: "نیک پی", parent: 24, code: 617 },
  { name: "Soltaniyeh", title: "سلطانیه", parent: 24, code: 618 },
  { name: "Abbar", title: "آب بر", parent: 24, code: 619 },
  { name: "Chavarzaq", title: "چورزق", parent: 24, code: 620 },
  { name: "Dandi", title: "دندی", parent: 24, code: 621 },
  { name: "Mahneshan", title: "ماه نشان", parent: 24, code: 622 },
  { name: "Aradan", title: "آرادان", parent: 23, code: 623 },
  { name: "Kohanabad", title: "کهن آباد", parent: 23, code: 624 },
  { name: "Amiriyeh", title: "امیریه", parent: 23, code: 625 },
  { name: "Damghan", title: "دامغان", parent: 23, code: 626 },
  { name: "Dibaj", title: "دیباج", parent: 23, code: 627 },
  { name: "Kalateh", title: "کلاته", parent: 23, code: 628 },
  { name: "Sorkheh", title: "سرخه", parent: 23, code: 629 },
  { name: "Semnan", title: "سمنان", parent: 23, code: 630 },
  { name: "Bastam", title: "بسطام", parent: 23, code: 631 },
  { name: "Beyarjomand", title: "بیارجمند", parent: 23, code: 632 },
  { name: "Rudian", title: "رودیان", parent: 23, code: 633 },
  { name: "Shahrud", title: "شاهرود", parent: 23, code: 634 },
  { name: "KalatehyeKhij", title: "کلاته خیج", parent: 23, code: 635 },
  { name: "Mojen", title: "مجن", parent: 23, code: 636 },
  { name: "Eyvanki", title: "ایوانکی", parent: 23, code: 637 },
  { name: "Garmsar", title: "گرمسار", parent: 23, code: 638 },
  { name: "Darjazin", title: "درجزین", parent: 23, code: 639 },
  { name: "Shahmirzad", title: "شهمیرزاد", parent: 23, code: 640 },
  { name: "MehdiShahr", title: "مهدی شهر", parent: 23, code: 641 },
  { name: "Meyami", title: "میامی", parent: 23, code: 642 },
  { name: "Iranshahr", title: "ایرانشهر", parent: 54, code: 643 },
  { name: "Bazman", title: "بزمان", parent: 54, code: 644 },
  { name: "Bampur", title: "بمپور", parent: 54, code: 645 },
  { name: "Mohammadan", title: "محمدان", parent: 54, code: 646 },
  { name: "Chabahar", title: "چابهار", parent: 54, code: 647 },
  { name: "Negur", title: "نگور", parent: 54, code: 648 },
  { name: "Khash", title: "خاش", parent: 54, code: 649 },
  { name: "Nukabad", title: "نوک آباد", parent: 54, code: 650 },
  { name: "Golmurti", title: "گلمورتی", parent: 54, code: 651 },
  { name: "Bonjar", title: "بنجار", parent: 54, code: 652 },
  { name: "Zabol", title: "زابل", parent: 54, code: 653 },
  { name: "Zahedan", title: "زاهدان", parent: 54, code: 654 },
  { name: "Nosratabad", title: "نصرت آباد", parent: 54, code: 655 },
  { name: "Zehak", title: "زهک", parent: 54, code: 656 },
  { name: "Jaleq", title: "جالق", parent: 54, code: 657 },
  { name: "Saravan", title: "سراوان", parent: 54, code: 658 },
  { name: "Sirkan", title: "سیرکان", parent: 54, code: 659 },
  { name: "Gosht", title: "گشت", parent: 54, code: 660 },
  { name: "Mohamadi", title: "محمدی", parent: 54, code: 661 },
  { name: "Pishin", title: "پیشین", parent: 54, code: 662 },
  { name: "Rask", title: "راسک", parent: 54, code: 663 },
  { name: "Sarbaz", title: "سرباز", parent: 54, code: 664 },
  { name: "Suran", title: "سوران", parent: 54, code: 665 },
  { name: "Hiduch", title: "هیدوچ", parent: 54, code: 666 },
  { name: "Fanuj", title: "فنوج", parent: 54, code: 667 },
  { name: "QasreQand", title: "قصرقند", parent: 54, code: 668 },
  { name: "Zarabade", title: "زرآباد", parent: 54, code: 669 },
  { name: "Konarak", title: "کنارک", parent: 54, code: 670 },
  { name: "Zaboli", title: "مهرستان", parent: 54, code: 671 },
  { name: "Mirjaveh", title: "میرجاوه", parent: 54, code: 672 },
  { name: "Espakeh", title: "اسپکه", parent: 54, code: 673 },
  { name: "Bent", title: "بنت", parent: 54, code: 674 },
  { name: "NikShahr", title: "نیک شهر", parent: 54, code: 675 },
  { name: "Adimi", title: "ادیمی", parent: 54, code: 676 },
  { name: "Akbarabad", title: "شهرک علی اکبر", parent: 54, code: 677 },
  { name: "Mohammadabad", title: "محمدآباد", parent: 54, code: 678 },
  { name: "DustMohammad", title: "دوست محمد", parent: 54, code: 679 },
  { name: "Abadeh", title: "آباده", parent: 71, code: 680 },
  { name: "Izadkhast", title: "ایزدخواست", parent: 71, code: 681 },
  { name: "Bahman", title: "بهمن", parent: 71, code: 682 },
  { name: "Surmaq", title: "سورمق", parent: 71, code: 683 },
  { name: "Soghad", title: "صغاد", parent: 71, code: 684 },
  { name: "Arsanjan", title: "ارسنجان", parent: 71, code: 685 },
  { name: "Estahban", title: "استهبان", parent: 71, code: 686 },
  { name: "Ij", title: "ایج", parent: 71, code: 687 },
  { name: "Runiz", title: "رونیز", parent: 71, code: 688 },
  { name: "Eqlid", title: "اقلید", parent: 71, code: 689 },
  { name: "Hassanabad", title: "حسن اباد", parent: 71, code: 690 },
  { name: "Dehenow", title: "دژکرد", parent: 71, code: 691 },
  { name: "Sedeh", title: "سده", parent: 71, code: 692 },
  { name: "Bavanat", title: "بوانات", parent: 71, code: 693 },
  { name: "Hesami", title: "حسامی", parent: 71, code: 694 },
  { name: "Korrehi", title: "کره ای", parent: 71, code: 695 },
  { name: "Mazayjan", title: "مزایجان", parent: 71, code: 696 },
  { name: "SaadatShahr", title: "سعادت شهر", parent: 71, code: 697 },
  { name: "MadareSoleyman", title: "مادرسلیمان", parent: 71, code: 698 },
  { name: "BabAnar", title: "باب انار", parent: 71, code: 699 },
  { name: "Jahrom", title: "جهرم", parent: 71, code: 700 },
  { name: "Khavaran", title: "خاوران", parent: 71, code: 701 },
  { name: "Duzeh", title: "دوزه", parent: 71, code: 702 },
  { name: "Qotbabad", title: "قطب آباد", parent: 71, code: 703 },
  { name: "Kharameh", title: "خرامه", parent: 71, code: 704 },
  { name: "SoltanShahr", title: "سلطان شهر", parent: 71, code: 705 },
  { name: "Safashahr", title: "صفاشهر", parent: 71, code: 706 },
  { name: "Qaderabad", title: "قادراباد", parent: 71, code: 707 },
  { name: "Khonj", title: "خنج", parent: 71, code: 708 },
  { name: "JannatShahr", title: "جنت شهر", parent: 71, code: 709 },
  { name: "Darab", title: "داراب", parent: 71, code: 710 },
  { name: "Doborji", title: "دوبرجی", parent: 71, code: 711 },
  { name: "Fadami", title: "فدامی", parent: 71, code: 712 },
  { name: "Kopen", title: "کوپن", parent: 71, code: 713 },
  { name: "Masiri", title: "مصیری", parent: 71, code: 714 },
  { name: "Hajiabad", title: "حاجی آباد", parent: 71, code: 715 },
  { name: "Dobiran", title: "دبیران", parent: 71, code: 716 },
  { name: "PirCity", title: "شهرپیر", parent: 71, code: 717 },
  { name: "Ardakan", title: "اردکان", parent: 71, code: 718 },
  { name: "Beyza", title: "بیضا", parent: 71, code: 719 },
  { name: "Hamashahr", title: "هماشهر", parent: 71, code: 720 },
  { name: "Sarvestan", title: "سروستان", parent: 71, code: 721 },
  { name: "Kuhenjan", title: "کوهنجان", parent: 71, code: 722 },
  { name: "KhanehZenyan", title: "خانه زنیان", parent: 71, code: 723 },
  { name: "Darian", title: "داریان", parent: 71, code: 724 },
  { name: "Zarqan", title: "زرقان", parent: 71, code: 725 },
  { name: "Sadra", title: "صدرا", parent: 71, code: 726 },
  { name: "Shiraz", title: "شیراز", parent: 71, code: 727 },
  { name: "Lapui", title: "لپویی", parent: 71, code: 728 },
  { name: "Dehram", title: "دهرم", parent: 71, code: 729 },
  { name: "Farashband", title: "فراشبند", parent: 71, code: 730 },
  { name: "Nowjeyn", title: "نوجین", parent: 71, code: 731 },
  { name: "Zahedshahr", title: "زاهدشهر", parent: 71, code: 732 },
  { name: "Sheshdeh", title: "ششده", parent: 71, code: 733 },
  { name: "Fasa", title: "فسا", parent: 71, code: 734 },
  { name: "QarahBolagh", title: "قره بلاغ", parent: 71, code: 735 },
  { name: "Miyanshahr", title: "میانشهر", parent: 71, code: 736 },
  { name: "NoBandegan", title: "نوبندگان", parent: 71, code: 737 },
  { name: "Firuzabad", title: "فیروزآباد", parent: 71, code: 738 },
  { name: "Meymand", title: "میمند", parent: 71, code: 739 },
  { name: "Efzar", title: "افزر", parent: 71, code: 740 },
  { name: "EmamShahr", title: "امام شهر", parent: 71, code: 741 },
  { name: "Qir", title: "قیر", parent: 71, code: 742 },
  { name: "Karzin", title: "کارزین", parent: 71, code: 743 },
  { name: "Mobarakabad", title: "مبارک آباددیز", parent: 71, code: 744 },
  { name: "Baladeh", title: "بالاده", parent: 71, code: 745 },
  { name: "Khesht", title: "خشت", parent: 71, code: 746 },
  { name: "Qaemiyeh", title: "قایمیه", parent: 71, code: 747 },
  { name: "Kazerun", title: "کازرون", parent: 71, code: 748 },
  { name: "Konartakhteh", title: "کنارتخته", parent: 71, code: 749 },
  { name: "Nowdan", title: "نودان", parent: 71, code: 750 },
  { name: "Kavar", title: "کوار", parent: 71, code: 751 },
  { name: "Gerash", title: "گراش", parent: 71, code: 752 },
  { name: "Owz", title: "اوز", parent: 71, code: 753 },
  { name: "Banaruyeh", title: "بنارویه", parent: 71, code: 754 },
  { name: "Beyram", title: "بیرم", parent: 71, code: 755 },
  { name: "Juyom", title: "جویم", parent: 71, code: 756 },
  { name: "Khure", title: "خور", parent: 71, code: 757 },
  { name: "EmadDeh", title: "عمادده", parent: 71, code: 758 },
  { name: "Lar", title: "لار", parent: 71, code: 759 },
  { name: "Latifi", title: "لطیفی", parent: 71, code: 760 },
  { name: "Ashkanan", title: "اشکنان", parent: 71, code: 761 },
  { name: "Ahel", title: "اهل", parent: 71, code: 762 },
  { name: "Alamarvdasht", title: "علامرودشت", parent: 71, code: 763 },
  { name: "Lamerd", title: "لامرد", parent: 71, code: 764 },
  { name: "Khaniman", title: "خانیمن", parent: 71, code: 765 },
  { name: "Koushkak", title: "رامجرد", parent: 71, code: 766 },
  { name: "Seydan", title: "سیدان", parent: 71, code: 767 },
  { name: "Kamfiruz", title: "کامفیروز", parent: 71, code: 768 },
  { name: "Marvdasht", title: "مرودشت", parent: 71, code: 769 },
  { name: "BabaMonir", title: "بابامنیر", parent: 71, code: 770 },
  { name: "KhumehZar", title: "خومه زار", parent: 71, code: 771 },
  { name: "Nurabad", title: "نورآباد", parent: 71, code: 772 },
  { name: "Asir", title: "اسیر", parent: 71, code: 773 },
  { name: "Khuzi", title: "خوزی", parent: 71, code: 774 },
  { name: "GallehDar", title: "گله دار", parent: 71, code: 775 },
  { name: "Mohre", title: "مهر", parent: 71, code: 776 },
  { name: "Varavi", title: "وراوی", parent: 71, code: 777 },
  { name: "AbadehTashk", title: "آباده طشک", parent: 71, code: 778 },
  { name: "Qatruyeh", title: "قطرویه", parent: 71, code: 779 },
  { name: "Meshkan", title: "مشکان", parent: 71, code: 780 },
  { name: "Neyriz", title: "نی ریز", parent: 71, code: 781 },
  { name: "Abyek", title: "آبیک", parent: 28, code: 782 },
  { name: "Khakali", title: "خاکعلی", parent: 28, code: 783 },
  { name: "Abgarm", title: "آبگرم", parent: 28, code: 784 },
  { name: "Avaj", title: "آوج", parent: 28, code: 785 },
  { name: "Alvand", title: "الوند", parent: 28, code: 786 },
  { name: "Bidestan", title: "بیدستان", parent: 28, code: 787 },
  { name: "Sharifiyeh", title: "شریفیه", parent: 28, code: 788 },
  { name: "Mohammadiyeh", title: "محمدیه", parent: 28, code: 789 },
  { name: "Ardak", title: "ارداق", parent: 28, code: 790 },
  { name: "BuinZahra", title: "بویین زهرا", parent: 28, code: 791 },
  { name: "Danesfahan", title: "دانسفهان", parent: 28, code: 792 },
  { name: "Sagzabad", title: "سگزآباد", parent: 28, code: 793 },
  { name: "Shal", title: "شال", parent: 28, code: 794 },
  { name: "Asfarvarin", title: "اسفرورین", parent: 28, code: 795 },
  { name: "Takestan", title: "تاکستان", parent: 28, code: 796 },
  { name: "Khorramdasht", title: "خرمدشت", parent: 28, code: 797 },
  { name: "Ziaabad", title: "ضیاڈآباد", parent: 28, code: 798 },
  { name: "Narjeh", title: "نرجه", parent: 28, code: 799 },
  { name: "Eqbaliyeh", title: "اقبالیه", parent: 28, code: 800 },
  { name: "Razmian", title: "رازمیان", parent: 28, code: 801 },
  { name: "Sirdan", title: "سیردان", parent: 28, code: 802 },
  { name: "Qazvin", title: "قزوین", parent: 28, code: 803 },
  { name: "Kuhin", title: "کوهین", parent: 28, code: 804 },
  {
    name: "MahmudabadNemuneh",
    title: "محمود آباد نمونه",
    parent: 28,
    code: 805,
  },
  { name: "MoallemKelayeh", title: "معلم کلایه", parent: 28, code: 806 },
  { name: "Jafariyeh", title: "جعفریه", parent: 25, code: 807 },
  { name: "Dastjerd", title: "دستجرد", parent: 25, code: 808 },
  { name: "Salafchegan", title: "سلفچگان", parent: 25, code: 809 },
  { name: "Qom", title: "قم", parent: 25, code: 810 },
  { name: "Qanavat", title: "قنوات", parent: 25, code: 811 },
  { name: "Kahak", title: "کهک", parent: 25, code: 812 },
  { name: "Armardeh", title: "آرمرده", parent: 87, code: 813 },
  { name: "Baneh", title: "بانه", parent: 87, code: 814 },
  { name: "BoeeneSofla", title: "بویین سفلی", parent: 87, code: 815 },
  { name: "KaniSur", title: "کانی سور", parent: 87, code: 816 },
  { name: "Babarashani", title: "بابارشانی", parent: 87, code: 817 },
  { name: "Bijar", title: "بیجار", parent: 87, code: 818 },
  { name: "PirTaj", title: "پیرتاج", parent: 87, code: 819 },
  { name: "TupAghaj", title: "توپ آغاج", parent: 87, code: 820 },
  { name: "Yasukand", title: "یاسوکند", parent: 87, code: 821 },
  { name: "Bolbanabad", title: "بلبان آباد", parent: 87, code: 822 },
  { name: "Dehgolan", title: "دهگلان", parent: 87, code: 823 },
  { name: "Divandarreh", title: "دیواندره", parent: 87, code: 824 },
  { name: "Zarrineh", title: "زرینه", parent: 87, code: 825 },
  { name: "AavramanTakht", title: "اورامان تخت", parent: 87, code: 826 },
  { name: "Sarvabad", title: "سروآباد", parent: 87, code: 827 },
  { name: "Saqqez", title: "سقز", parent: 87, code: 828 },
  { name: "Saheb", title: "صاحب", parent: 87, code: 829 },
  { name: "Sanandaj", title: "سنندج", parent: 87, code: 830 },
  { name: "Shuyesheh", title: "شویشه", parent: 87, code: 831 },
  { name: "Dezej", title: "دزج", parent: 87, code: 832 },
  { name: "Delbaran", title: "دلبران", parent: 87, code: 833 },
  { name: "Serishabad", title: "سریش آباد", parent: 87, code: 834 },
  { name: "Qorveh", title: "قروه", parent: 87, code: 835 },
  { name: "Kamyaran", title: "کامیاران", parent: 87, code: 836 },
  { name: "Muchesh", title: "موچش", parent: 87, code: 837 },
  { name: "BardehRasheh", title: "برده رشه", parent: 87, code: 838 },
  { name: "Chenareh", title: "چناره", parent: 87, code: 839 },
  { name: "KaniDinar", title: "کانی دینار", parent: 87, code: 840 },
  { name: "Marivan", title: "مریوان", parent: 87, code: 841 },
  { name: "Orzueeyeh", title: "ارزوییه", parent: 34, code: 842 },
  { name: "AminShahr", title: "امین شهر", parent: 34, code: 843 },
  { name: "Anar", title: "انار", parent: 34, code: 844 },
  { name: "Baft", title: "بافت", parent: 34, code: 845 },
  { name: "Bezenjan", title: "بزنجان", parent: 34, code: 846 },
  { name: "Bardsir", title: "بردسیر", parent: 34, code: 847 },
  { name: "Dashtkar", title: "دشتکار", parent: 34, code: 848 },
  { name: "Golzar", title: "گلزار", parent: 34, code: 849 },
  { name: "Lalehzar", title: "لاله زار", parent: 34, code: 850 },
  { name: "Negar", title: "نگار", parent: 34, code: 851 },
  { name: "Baravat", title: "بروات", parent: 34, code: 852 },
  { name: "Bam", title: "بم", parent: 34, code: 853 },
  { name: "Boluk", title: "بلوک", parent: 34, code: 854 },
  { name: "Jebalbarez", title: "جبالبارز", parent: 34, code: 855 },
  { name: "Jiroft", title: "جیرفت", parent: 34, code: 856 },
  { name: "DarbeBehesht", title: "درب بهشت", parent: 34, code: 857 },
  { name: "Rabor", title: "رابر", parent: 34, code: 858 },
  { name: "Hanza", title: "هنزا", parent: 34, code: 859 },
  { name: "Ravar", title: "راور", parent: 34, code: 860 },
  { name: "Hojdak", title: "هجدک", parent: 34, code: 861 },
  { name: "Bahreman", title: "بهرمان", parent: 34, code: 862 },
  { name: "Rafsanjan", title: "رفسنجان", parent: 34, code: 863 },
  { name: "Safayyeh", title: "صفاییه", parent: 34, code: 864 },
  { name: "Koshkoueieh", title: "کشکوییه", parent: 34, code: 865 },
  { name: "MeseSarcheshmeh", title: "مس سرچشمه", parent: 34, code: 866 },
  { name: "Rudbar", title: "رودبار", parent: 34, code: 867 },
  { name: "Zehkalut", title: "زهکلوت", parent: 34, code: 868 },
  { name: "Gonbaki", title: "گنبکی", parent: 34, code: 869 },
  { name: "Mohammadabaad", title: "محمدآباد", parent: 34, code: 870 },
  { name: "Khanuk", title: "خانوک", parent: 34, code: 871 },
  { name: "Rijan", title: "ریحان", parent: 34, code: 872 },
  { name: "Zarand", title: "زرند", parent: 34, code: 873 },
  { name: "YazdanShahr", title: "یزدان شهر", parent: 34, code: 874 },
  { name: "Balvard", title: "بلورد", parent: 34, code: 875 },
  { name: "Pariz", title: "پاریز", parent: 34, code: 876 },
  { name: "KhvajuShahr", title: "خواجو شهر", parent: 34, code: 877 },
  { name: "Zeydabad", title: "زیدآباد", parent: 34, code: 878 },
  { name: "Sirjan", title: "سیرجان", parent: 34, code: 879 },
  { name: "NajafShahr", title: "نجف شهر", parent: 34, code: 880 },
  { name: "Hamashahre", title: "هماشهر", parent: 34, code: 881 },
  { name: "Jowzam", title: "جوزم", parent: 34, code: 882 },
  { name: "Khatunabad", title: "خاتون اباد", parent: 34, code: 883 },
  { name: "Khursand", title: "خورسند", parent: 34, code: 884 },
  { name: "Dehaj", title: "دهج", parent: 34, code: 885 },
  { name: "ShahreBabak", title: "شهر بابک", parent: 34, code: 886 },
  { name: "DowSari", title: "دوساری", parent: 34, code: 887 },
  { name: "Anbarabad", title: "عنبرآباد", parent: 34, code: 888 },
  { name: "Mardehek", title: "مردهک", parent: 34, code: 889 },
  { name: "Faryab", title: "فاریاب", parent: 34, code: 890 },
  { name: "Fahraj", title: "فهرج", parent: 34, code: 891 },
  { name: "QalehGanj", title: "قلعه گنج", parent: 34, code: 892 },
  { name: "Ekhtiarabad", title: "اختیارآباد", parent: 34, code: 893 },
  { name: "Anduhjerd", title: "اندوهجرد", parent: 34, code: 894 },
  { name: "Baghin", title: "باغین", parent: 34, code: 895 },
  { name: "Jupar", title: "جوپار", parent: 34, code: 896 },
  { name: "Chatrud", title: "چترود", parent: 34, code: 897 },
  { name: "Rayen", title: "راین", parent: 34, code: 898 },
  { name: "Zangiabad", title: "زنگی آباد", parent: 34, code: 899 },
  { name: "Shahdad", title: "شهداد", parent: 34, code: 900 },
  { name: "Kazemabad", title: "کاظم آباد", parent: 34, code: 901 },
  { name: "Kerman", title: "کرمان", parent: 34, code: 902 },
  { name: "Golbaf", title: "گلباف", parent: 34, code: 903 },
  { name: "Mahan", title: "ماهان", parent: 34, code: 904 },
  { name: "Mohiabad", title: "محی آباد", parent: 34, code: 905 },
  { name: "Kuhbanan", title: "کوهبنان", parent: 34, code: 906 },
  { name: "KianShahr", title: "کیانشهر", parent: 34, code: 907 },
  { name: "Kahnuj", title: "کهنوج", parent: 34, code: 908 },
  { name: "Manujan", title: "منوجان", parent: 34, code: 909 },
  { name: "Nodej", title: "نودژ", parent: 34, code: 910 },
  { name: "Narmashir", title: "نرماشیر", parent: 34, code: 911 },
  { name: "Nezamabad", title: "نظام شهر", parent: 34, code: 912 },
  { name: "EslamabadeGharb", title: "اسلام آبادغرب", parent: 83, code: 913 },
  { name: "Hamil", title: "حمیل", parent: 83, code: 914 },
  { name: "Banevreh", title: "بانوره", parent: 83, code: 915 },
  { name: "Bayangan", title: "باینگان", parent: 83, code: 916 },
  { name: "Paveh", title: "پاوه", parent: 83, code: 917 },
  { name: "Nowdeshah", title: "نودشه", parent: 83, code: 918 },
  { name: "Nowsud", title: "نوسود", parent: 83, code: 919 },
  { name: "Ozgoleh", title: "ازگله", parent: 83, code: 920 },
  { name: "Tazehabad", title: "تازه آباد", parent: 83, code: 921 },
  { name: "Javanrud", title: "جوانرود", parent: 83, code: 922 },
  { name: "Rijab", title: "ریجاب", parent: 83, code: 923 },
  { name: "Karand", title: "کرند", parent: 83, code: 924 },
  { name: "Gahvareh", title: "گهواره", parent: 83, code: 925 },
  { name: "Ravansar", title: "روانسر", parent: 83, code: 926 },
  { name: "Shahu", title: "شاهو", parent: 83, code: 927 },
  { name: "SarpoleZahab", title: "سرپل ذهاب", parent: 83, code: 928 },
  { name: "Satar", title: "سطر", parent: 83, code: 929 },
  { name: "Sonqor", title: "سنقر", parent: 83, code: 930 },
  { name: "Sahneh", title: "صحنه", parent: 83, code: 931 },
  { name: "MianRahan", title: "میان راهان", parent: 83, code: 932 },
  { name: "Sumar", title: "سومار", parent: 83, code: 933 },
  { name: "QasreShirin", title: "قصرشیرین", parent: 83, code: 934 },
  { name: "Rabat", title: "رباط", parent: 83, code: 935 },
  { name: "Kermanshah", title: "کرمانشاه", parent: 83, code: 936 },
  { name: "Kuzaran", title: "کوزران", parent: 83, code: 937 },
  { name: "Halashi", title: "هلشی", parent: 83, code: 938 },
  { name: "Kangavar", title: "کنگاور", parent: 83, code: 939 },
  { name: "Gowdin", title: "گودین", parent: 83, code: 940 },
  { name: "Sarmast", title: "سرمست", parent: 83, code: 941 },
  { name: "GilaneGharb", title: "گیلانغرب", parent: 83, code: 942 },
  { name: "Bisotun", title: "بیستون", parent: 83, code: 943 },
  { name: "Harsin", title: "هرسین", parent: 83, code: 944 },
  { name: "Basht", title: "باشت", parent: 74, code: 945 },
  { name: "Chitab", title: "چیتاب", parent: 74, code: 946 },
  { name: "GarabeSofla", title: "گراب سفلی", parent: 74, code: 947 },
  { name: "Madavan", title: "مادوان", parent: 74, code: 948 },
  { name: "Margown", title: "مارگون", parent: 74, code: 949 },
  { name: "Yasuj", title: "یاسوج", parent: 74, code: 950 },
  { name: "Likak", title: "لیکک", parent: 74, code: 951 },
  { name: "Charam", title: "چرام", parent: 74, code: 952 },
  { name: "Sarfaryab", title: "سرفاریاب", parent: 74, code: 953 },
  { name: "Pataveh", title: "پاتاوه", parent: 74, code: 954 },
  { name: "Sisakht", title: "سی سخت", parent: 74, code: 955 },
  { name: "Dehdasht", title: "دهدشت", parent: 74, code: 956 },
  { name: "Dishmok", title: "دیشموک", parent: 74, code: 957 },
  { name: "Suq", title: "سوق", parent: 74, code: 958 },
  { name: "QalehRaisi", title: "قلعه رییسی", parent: 74, code: 959 },
  { name: "Dogonbadan", title: "دوگنبدان", parent: 74, code: 960 },
  { name: "Landeh", title: "لنده", parent: 74, code: 961 },
  { name: "Azadshahr", title: "آزادشهر", parent: 17, code: 962 },
  { name: "Neginshahr", title: "نگین شهر", parent: 17, code: 963 },
  { name: "NowdehKhanduz", title: "نوده خاندوز", parent: 17, code: 964 },
  { name: "AqQala", title: "آق قلا", parent: 17, code: 965 },
  { name: "AnbarOlum", title: "انبارآلوم", parent: 17, code: 966 },
  { name: "BandareGaz", title: "بندرگز", parent: 17, code: 967 },
  { name: "Nowkandeh", title: "نوکنده", parent: 17, code: 968 },
  { name: "BandarTorkaman", title: "بندرترکمن", parent: 17, code: 969 },
  { name: "TatarOlia", title: "تاتارعلیا", parent: 17, code: 970 },
  { name: "KhanBebin", title: "خان ببین", parent: 17, code: 971 },
  { name: "Daland", title: "دلند", parent: 17, code: 972 },
  { name: "Ramian", title: "رامیان", parent: 17, code: 973 },
  { name: "Sangdevin", title: "سنگدوین", parent: 17, code: 974 },
  { name: "AliabadeKatul", title: "علی ‌آباد کتول", parent: 17, code: 975 },
  { name: "Fazelabad", title: "فاضل آباد", parent: 17, code: 976 },
  { name: "Mazraeh", title: "مزرعه", parent: 17, code: 977 },
  { name: "Kordkuy", title: "کردکوی", parent: 17, code: 978 },
  { name: "Faraghi", title: "فراغی", parent: 17, code: 979 },
  { name: "Kalaleh", title: "کلاله", parent: 17, code: 980 },
  { name: "Galikash", title: "گالیکش", parent: 17, code: 981 },
  { name: "JelineOlya", title: "جلین", parent: 17, code: 982 },
  { name: "SarkhonKalateh", title: "سرخنکلاته", parent: 17, code: 983 },
  { name: "Gorgan", title: "گرگان", parent: 17, code: 984 },
  { name: "SiminShahr", title: "سیمین شهر", parent: 17, code: 985 },
  { name: "Kumushdepe", title: "گمیش تپه", parent: 17, code: 986 },
  { name: "Incheboron", title: "اینچه برون", parent: 17, code: 987 },
  { name: "GonbadKavus", title: "گنبدکاووس", parent: 17, code: 988 },
  { name: "MaravehTappeh", title: "مراوه", parent: 17, code: 989 },
  { name: "Minudasht", title: "مینودشت", parent: 17, code: 990 },
  { name: "Astara", title: "آستارا", parent: 13, code: 991 },
  { name: "Lavandevil", title: "لوندویل", parent: 13, code: 992 },
  {
    name: "AstanehyeAshrafiyeh",
    title: "آستانه اشرفیه",
    parent: 13,
    code: 993,
  },
  { name: "Kiashahr", title: "کیاشهر", parent: 13, code: 994 },
  { name: "Amlash", title: "املش", parent: 13, code: 995 },
  { name: "Rankuh", title: "رانکوه", parent: 13, code: 996 },
  { name: "BandareAnzali", title: "بندرانزلی", parent: 13, code: 997 },
  { name: "KhoshkeBijar", title: "خشکبیجار", parent: 13, code: 998 },
  { name: "Khomam", title: "خمام", parent: 13, code: 999 },
  { name: "Rasht", title: "رشت", parent: 13, code: 1000 },
  { name: "Sangar", title: "سنگر", parent: 13, code: 1001 },
  { name: "Kuchesfahan", title: "کوچصفهان", parent: 13, code: 1002 },
  { name: "LashteNesha", title: "لشت نشاء", parent: 13, code: 1003 },
  { name: "Loleman", title: "لولمان", parent: 13, code: 1004 },
  { name: "ParehSar", title: "پره سر", parent: 13, code: 1005 },
  { name: "Rezvanshahre", title: "رضوانشهر", parent: 13, code: 1006 },
  { name: "Barehsar", title: "بره سر", parent: 13, code: 1007 },
  { name: "Tutkabon", title: "توتکابن", parent: 13, code: 1008 },
  { name: "Jirandeh", title: "جیرنده", parent: 13, code: 1009 },
  { name: "Rostamabad", title: "رستم آباد", parent: 13, code: 1010 },
  { name: "Rudbaar", title: "رودبار", parent: 13, code: 1011 },
  { name: "Lowshan", title: "لوشان", parent: 13, code: 1012 },
  { name: "Manjil", title: "منجیل", parent: 13, code: 1013 },
  { name: "Chaboksar", title: "چابکسر", parent: 13, code: 1014 },
  { name: "Rahimabad", title: "رحیم آباد", parent: 13, code: 1015 },
  { name: "Rudsar", title: "رودسر", parent: 13, code: 1016 },
  { name: "Kelachay", title: "کلاچای", parent: 13, code: 1017 },
  { name: "Vajargah", title: "واجارگاه", parent: 13, code: 1018 },
  { name: "Deylaman", title: "دیلمان", parent: 13, code: 1019 },
  { name: "Siahkal", title: "سیاهکل", parent: 13, code: 1020 },
  { name: "Ahmadsargurab", title: "احمدسرگوراب", parent: 13, code: 1021 },
  { name: "Sharaft", title: "شفت", parent: 13, code: 1022 },
  { name: "SowmeehSara", title: "صومعه سرا", parent: 13, code: 1023 },
  { name: "GurabZarmikh", title: "گوراب زرمیخ", parent: 13, code: 1024 },
  { name: "Marjaghal", title: "مرجقل", parent: 13, code: 1025 },
  { name: "Asalem", title: "اسالم", parent: 13, code: 1026 },
  { name: "Chubar", title: "چوبر", parent: 13, code: 1027 },
  { name: "Haviq", title: "حویق", parent: 13, code: 1028 },
  { name: "Lisar", title: "لیسار", parent: 13, code: 1029 },
  { name: "Hashtpar", title: "هشتپر", parent: 13, code: 1030 },
  { name: "Fuman", title: "فومن", parent: 13, code: 1031 },
  { name: "Masuleh", title: "ماسوله", parent: 13, code: 1032 },
  { name: "Maklavan", title: "ماکلوان", parent: 13, code: 1033 },
  { name: "Rudboneh", title: "رودبنه", parent: 13, code: 1034 },
  { name: "Lahijan", title: "لاهیجان", parent: 13, code: 1035 },
  { name: "Otaghvar", title: "اطاقور", parent: 13, code: 1036 },
  { name: "ChafandChamkhaleh", title: "چاف و چمخاله", parent: 13, code: 1037 },
  { name: "Shalman", title: "شلمان", parent: 13, code: 1038 },
  { name: "Kumeleh", title: "کومله", parent: 13, code: 1039 },
  { name: "Langarud", title: "لنگرود", parent: 13, code: 1040 },
  { name: "BazarJomeh", title: "بازار جمعه", parent: 13, code: 1041 },
  { name: "Masal", title: "ماسال", parent: 13, code: 1042 },
  { name: "Azna", title: "ازنا", parent: 66, code: 1043 },
  { name: "Momenabad", title: "مومن آباد", parent: 66, code: 1044 },
  { name: "Aligudarz", title: "الیگودرز", parent: 66, code: 1045 },
  { name: "ShoolAbad", title: "شول آباد", parent: 66, code: 1046 },
  { name: "Oshtorinan", title: "اشترینان", parent: 66, code: 1047 },
  { name: "Borujerd", title: "بروجرد", parent: 66, code: 1048 },
  { name: "PolDokhtar", title: "پلدختر", parent: 66, code: 1049 },
  { name: "Mamulan", title: "معمولان", parent: 66, code: 1050 },
  { name: "Bayranshahr", title: "بیران شهر", parent: 66, code: 1051 },
  { name: "Khorramabad", title: "خرم آباد", parent: 66, code: 1052 },
  { name: "Zagheh", title: "زاغه", parent: 66, code: 1053 },
  { name: "Sepiddasht", title: "سپیددشت", parent: 66, code: 1054 },
  { name: "Noorabad", title: "نورآباد", parent: 66, code: 1055 },
  { name: "HaftCheshmeh", title: "هفت چشمه", parent: 66, code: 1056 },
  { name: "Chalanchulan", title: "چالانچولان", parent: 66, code: 1057 },
  { name: "Dorud", title: "دورود", parent: 66, code: 1058 },
  { name: "SarabeDowreh", title: "سراب دوره", parent: 66, code: 1059 },
  { name: "Veysian", title: "ویسیان", parent: 66, code: 1060 },
  { name: "Chaqabol", title: "چقابل", parent: 66, code: 1061 },
  { name: "Aleshtar", title: "الشتر", parent: 66, code: 1062 },
  { name: "Firoozabad", title: "فیروزآباد", parent: 66, code: 1063 },
  { name: "DarbeGonbad", title: "درب گنبد", parent: 66, code: 1064 },
  { name: "Kuhdasht", title: "کوهدشت", parent: 66, code: 1065 },
  { name: "Kunani", title: "کوهنانی", parent: 66, code: 1066 },
  { name: "Garab", title: "گراب", parent: 66, code: 1067 },
  { name: "Amol", title: "آمل", parent: 11, code: 1068 },
  {
    name: "AmamzadehAbdallah",
    title: "امامزاده عبدالله",
    parent: 11,
    code: 1069,
  },
  { name: "Dabudasht", title: "دابودشت", parent: 11, code: 1070 },
  { name: "Rineh", title: "رینه", parent: 11, code: 1071 },
  { name: "Gazanak", title: "گزنک", parent: 11, code: 1072 },
  { name: "Amirkola", title: "امیرکلا", parent: 11, code: 1073 },
  { name: "Babol", title: "بابل", parent: 11, code: 1074 },
  { name: "KhushRudpey", title: "خوش رودپی", parent: 11, code: 1075 },
  { name: "Zargarmahalleh", title: "زرگرمحله", parent: 11, code: 1076 },
  { name: "Gatab", title: "گتاب", parent: 11, code: 1077 },
  { name: "Galugah", title: "گلوگاه", parent: 11, code: 1078 },
  { name: "Marzikola", title: "مرزیکلا", parent: 11, code: 1079 },
  { name: "Babolsar", title: "بابلسر", parent: 11, code: 1080 },
  { name: "Bahnamir", title: "بهنمیر", parent: 11, code: 1081 },
  { name: "HadiShahr", title: "هادی شهر", parent: 11, code: 1082 },
  { name: "Behshahr", title: "بهشهر", parent: 11, code: 1083 },
  { name: "KhalilShahr", title: "خلیل شهر", parent: 11, code: 1084 },
  { name: "Rostamkola", title: "رستمکلا", parent: 11, code: 1085 },
  { name: "Tonekabon", title: "تنکابن", parent: 11, code: 1086 },
  { name: "Khoramabad", title: "خرم آباد", parent: 11, code: 1087 },
  { name: "Shirud", title: "شیرود", parent: 11, code: 1088 },
  { name: "Nashtarud", title: "نشتارود", parent: 11, code: 1089 },
  { name: "Juybar", title: "جویبار", parent: 11, code: 1090 },
  { name: "KuhiKheyl", title: "کوهی خیل", parent: 11, code: 1091 },
  { name: "Chalus", title: "چالوس", parent: 11, code: 1092 },
  { name: "Marzanabad", title: "مرزن آباد", parent: 11, code: 1093 },
  { name: "Hachirud", title: "هچیرود", parent: 11, code: 1094 },
  { name: "Ramsar", title: "رامسر", parent: 11, code: 1095 },
  { name: "Katalom", title: "کتالم و سادات شهر", parent: 11, code: 1096 },
  { name: "PaeinHoular", title: "پایین هولار", parent: 11, code: 1097 },
  { name: "Sari", title: "ساری", parent: 11, code: 1098 },
  { name: "Farim", title: "فریم", parent: 11, code: 1099 },
  { name: "Kiasar", title: "کیاسر", parent: 11, code: 1100 },
  { name: "Alasht", title: "آلاشت", parent: 11, code: 1101 },
  { name: "PolSefid", title: "پل سفید", parent: 11, code: 1102 },
  { name: "Zirab", title: "زیرآب", parent: 11, code: 1103 },
  { name: "Shirgah", title: "شیرگاه", parent: 11, code: 1104 },
  { name: "KiaKola", title: "کیاکلا", parent: 11, code: 1105 },
  { name: "SalmanShahr", title: "سلمان شهر", parent: 11, code: 1106 },
  { name: "Abbasabad", title: "عباس اباد", parent: 11, code: 1107 },
  { name: "Kelarabad", title: "کلارآباد", parent: 11, code: 1108 },
  { name: "Fereydunkenar", title: "فریدونکنار", parent: 11, code: 1109 },
  { name: "Arateh", title: "ارطه", parent: 11, code: 1110 },
  { name: "Qaemshahr", title: "قایم شهر", parent: 11, code: 1111 },
  { name: "Kelardasht", title: "کلاردشت", parent: 11, code: 1112 },
  { name: "Galoogah", title: "گلوگاه", parent: 11, code: 1113 },
  { name: "Sorkhrud", title: "سرخرود", parent: 11, code: 1114 },
  { name: "Mahmoodabad", title: "محمودآباد", parent: 11, code: 1115 },
  { name: "Surak", title: "سورک", parent: 11, code: 1116 },
  { name: "Neka", title: "نکا", parent: 11, code: 1117 },
  { name: "Izadshahr", title: "ایزدشهر", parent: 11, code: 1118 },
  { name: "Balade", title: "بلده", parent: 11, code: 1119 },
  { name: "Chamestan", title: "چمستان", parent: 11, code: 1120 },
  { name: "Royan", title: "رویان", parent: 11, code: 1121 },
  { name: "Nur", title: "نور", parent: 11, code: 1122 },
  { name: "Pul", title: "پول", parent: 11, code: 1123 },
  { name: "Kojur", title: "کجور", parent: 11, code: 1124 },
  { name: "Nowshahr", title: "نوشهر", parent: 11, code: 1125 },
  { name: "Ashtian", title: "آشتیان", parent: 86, code: 1126 },
  { name: "Arak", title: "اراک", parent: 86, code: 1127 },
  { name: "Davudabad", title: "داودآباد", parent: 86, code: 1128 },
  { name: "Saruq", title: "ساروق", parent: 86, code: 1129 },
  { name: "Karchan", title: "کارچان", parent: 86, code: 1130 },
  { name: "Tafresh", title: "تفرش", parent: 86, code: 1131 },
  { name: "Khomein", title: "خمین", parent: 86, code: 1132 },
  { name: "QurchiBashi", title: "قورچی باشی", parent: 86, code: 1133 },
  { name: "Javarseyan", title: "جاورسیان", parent: 86, code: 1134 },
  { name: "Khondab", title: "خنداب", parent: 86, code: 1135 },
  { name: "Delijan", title: "دلیجان", parent: 86, code: 1136 },
  { name: "Naraq", title: "نراق", parent: 86, code: 1137 },
  { name: "Parandak", title: "پرندک", parent: 86, code: 1138 },
  { name: "Khoshkrud", title: "خشکرود", parent: 86, code: 1139 },
  { name: "Razeqan", title: "رازقان", parent: 86, code: 1140 },
  { name: "Zaviyeh", title: "زاویه", parent: 86, code: 1141 },
  { name: "Mamuniyeh", title: "مامونیه", parent: 86, code: 1142 },
  { name: "Aveh", title: "آوه", parent: 86, code: 1143 },
  { name: "Saveh", title: "ساوه", parent: 86, code: 1144 },
  { name: "Gharqabad", title: "غرق آباد", parent: 86, code: 1145 },
  { name: "Nowbaran", title: "نوبران", parent: 86, code: 1146 },
  { name: "Astaneh", title: "آستانه", parent: 86, code: 1147 },
  { name: "Tureh", title: "توره", parent: 86, code: 1148 },
  { name: "Shazand", title: "شازند", parent: 86, code: 1149 },
  { name: "Shahbaz", title: "شهباز", parent: 86, code: 1150 },
  { name: "Mohajeran", title: "مهاجران", parent: 86, code: 1151 },
  { name: "Hendoudar", title: "هندودر", parent: 86, code: 1152 },
  { name: "Khenejin", title: "خنجین", parent: 86, code: 1153 },
  { name: "Farmahin", title: "فرمهین", parent: 86, code: 1154 },
  { name: "Komijan", title: "کمیجان", parent: 86, code: 1155 },
  { name: "Milajerd", title: "میلاجرد", parent: 86, code: 1156 },
  { name: "Mahallat", title: "محلات", parent: 86, code: 1157 },
  { name: "Nimvar", title: "نیمور", parent: 86, code: 1158 },
  { name: "AbuMusa", title: "ابوموسی", parent: 76, code: 1159 },
  { name: "Bastak", title: "بستک", parent: 76, code: 1160 },
  { name: "Janah", title: "جناح", parent: 76, code: 1161 },
  { name: "Saredashte", title: "سردشت", parent: 76, code: 1162 },
  { name: "Gowharan", title: "گوهران", parent: 76, code: 1163 },
  { name: "BandarAbbas", title: "بندرعباس", parent: 76, code: 1164 },
  { name: "Tazian", title: "تازیان پایین", parent: 76, code: 1165 },
  { name: "Takht", title: "تخت", parent: 76, code: 1166 },
  { name: "Fin", title: "فین", parent: 76, code: 1167 },
  { name: "QalehQazi", title: "قلعه قاضی", parent: 76, code: 1168 },
  { name: "BandarLengeh", title: "بندرلنگه", parent: 76, code: 1169 },
  { name: "BandareCharak", title: "چارک", parent: 76, code: 1170 },
  { name: "Kong", title: "کنگ", parent: 76, code: 1171 },
  { name: "Kish", title: "کیش", parent: 76, code: 1172 },
  { name: "Lamazan", title: "لمزان", parent: 76, code: 1173 },
  { name: "Parsian", title: "پارسیان", parent: 76, code: 1174 },
  { name: "Dashti", title: "دشتی", parent: 76, code: 1175 },
  { name: "Koshkonar", title: "کوشکنار", parent: 76, code: 1176 },
  { name: "BandareJask", title: "بندر جاسک", parent: 76, code: 1177 },
  { name: "Hajjiabade", title: "حاجی اباد", parent: 76, code: 1178 },
  { name: "Sargaz", title: "سرگز", parent: 76, code: 1179 },
  { name: "Fareghan", title: "فارغان", parent: 76, code: 1180 },
  { name: "Khamir", title: "خمیر", parent: 76, code: 1181 },
  { name: "Ruydar", title: "رویدر", parent: 76, code: 1182 },
  { name: "Bikah", title: "بیکاء", parent: 76, code: 1183 },
  { name: "Dehbarez", title: "دهبارز", parent: 76, code: 1184 },
  { name: "ZiarateAli", title: "زیارت علی", parent: 76, code: 1185 },
  { name: "Sirik", title: "سیریک", parent: 76, code: 1186 },
  { name: "Kouhestak", title: "کوهستک", parent: 76, code: 1187 },
  { name: "Garuk", title: "گروک", parent: 76, code: 1188 },
  { name: "Dargahan", title: "درگهان", parent: 76, code: 1189 },
  { name: "Suza", title: "سوزا", parent: 76, code: 1190 },
  { name: "Qeshm", title: "قشم", parent: 76, code: 1191 },
  { name: "Hormuz", title: "هرمز", parent: 76, code: 1192 },
  { name: "Tirur", title: "تیرور", parent: 76, code: 1193 },
  { name: "Senderk", title: "سندرک", parent: 76, code: 1194 },
  { name: "Minab", title: "میناب", parent: 76, code: 1195 },
  { name: "Hashtbandi", title: "هشتبندی", parent: 76, code: 1196 },
  { name: "Ajin", title: "آجین", parent: 81, code: 1197 },
  { name: "Asadabad", title: "اسدآباد", parent: 81, code: 1198 },
  { name: "Bahar", title: "بهار", parent: 81, code: 1199 },
  { name: "Saleabad", title: "صالح آباد", parent: 81, code: 1200 },
  { name: "Lalejin", title: "لالجین", parent: 81, code: 1201 },
  { name: "Mohaajeran", title: "مهاجران", parent: 81, code: 1202 },
  { name: "Tuyserkan", title: "تویسرکان", parent: 81, code: 1203 },
  { name: "Sarkan", title: "سرکان", parent: 81, code: 1204 },
  { name: "Farasfaj", title: "فرسفج", parent: 81, code: 1205 },
  { name: "Damaq", title: "دمق", parent: 81, code: 1206 },
  { name: "Razan", title: "رزن", parent: 81, code: 1207 },
  { name: "QorveheDarjazin", title: "قروه درجزین", parent: 81, code: 1208 },
  { name: "Famenin", title: "فامنین", parent: 81, code: 1209 },
  { name: "ShirinSu", title: "شیرین سو", parent: 81, code: 1210 },
  { name: "Kabudarahang", title: "کبودرآهنگ", parent: 81, code: 1211 },
  { name: "GolTappeh", title: "گل تپه", parent: 81, code: 1212 },
  { name: "Azandarian", title: "ازندریان", parent: 81, code: 1213 },
  { name: "Jowkar", title: "جوکار", parent: 81, code: 1214 },
  { name: "Zangeneh", title: "زنگنه", parent: 81, code: 1215 },
  { name: "Samen", title: "سامن", parent: 81, code: 1216 },
  { name: "Malayer", title: "ملایر", parent: 81, code: 1217 },
  { name: "Barzul", title: "برزول", parent: 81, code: 1218 },
  { name: "Firuzan", title: "فیروزان", parent: 81, code: 1219 },
  { name: "Giyan", title: "گیان", parent: 81, code: 1220 },
  { name: "Nahavand", title: "نهاوند", parent: 81, code: 1221 },
  { name: "Juraqan", title: "جورقان", parent: 81, code: 1222 },
  { name: "Qahavand", title: "قهاوند", parent: 81, code: 1223 },
  { name: "Maryanaj", title: "مریانج", parent: 81, code: 1224 },
  { name: "Hamadan", title: "همدان", parent: 81, code: 1225 },
  { name: "Abarkuh", title: "ابرکوه", parent: 35, code: 1226 },
  { name: "Mehrdasht", title: "مهردشت", parent: 35, code: 1227 },
  { name: "Ahmadeabad", title: "احمدآباد", parent: 35, code: 1228 },
  { name: "Ardakann", title: "اردکان", parent: 35, code: 1229 },
  { name: "Aqda", title: "عقدا", parent: 35, code: 1230 },
  { name: "Ashkezar", title: "اشکذر", parent: 35, code: 1231 },
  { name: "Khezrabad", title: "خضرآباد", parent: 35, code: 1232 },
  { name: "Bafq", title: "بافق", parent: 35, code: 1233 },
  { name: "Behabad", title: "بهاباد", parent: 35, code: 1234 },
  { name: "Taft", title: "تفت", parent: 35, code: 1235 },
  { name: "Niar", title: "نیر", parent: 35, code: 1236 },
  { name: "Marvast", title: "مروست", parent: 35, code: 1237 },
  { name: "Herat", title: "هرات", parent: 35, code: 1238 },
  { name: "Mehriz", title: "مهریز", parent: 35, code: 1239 },
  { name: "Bafruiyeh", title: "بفروییه", parent: 35, code: 1240 },
  { name: "Meybod", title: "میبد", parent: 35, code: 1241 },
  { name: "Nodoushan", title: "ندوشن", parent: 35, code: 1242 },
  { name: "Hamidiya", title: "حمیدیا", parent: 35, code: 1243 },
  { name: "Zarach", title: "زارچ", parent: 35, code: 1244 },
  { name: "Shahedieh", title: "شاهدیه", parent: 35, code: 1245 },
  { name: "Yazd", title: "یزد", parent: 35, code: 1246 },
];
