export const Provinces = [
  { name: "AzerbaijanEast", title: "آذربایجان شرقی", code: null, parent: 41 },
  { name: "AzerbaijanWest", title: "آذربایجان غربی", code: null, parent: 44 },
  { name: "Alborz", title: "البرز", code: null, parent: 26 },
  { name: "Ilam", title: "ایلام", code: null, parent: 84 },
  { name: "Ardabil", title: "اردبیل", code: null, parent: 45 },
  { name: "Isfahan", title: "اصفهان", code: null, parent: 31 },
  { name: "Bushehr", title: "بوشهر", code: null, parent: 77 },
  { name: "Tehran", title: "تهران", code: null, parent: 21 },
  {
    name: "ChaharMahaalandBakhtiari",
    title: "چهارمحال بختیاری",
    code: null,
    parent: 38,
  },
  { name: "KhorasanRazavi", title: "خراسان رضوی", code: null, parent: 51 },
  { name: "KhorasanSouth", title: "خراستان جنوبی", code: null, parent: 56 },
  { name: "KhorasanNorth", title: "خراسان شمالی", code: null, parent: 58 },
  { name: "Khuzestan", title: "خوزستان", code: null, parent: 61 },
  { name: "Zanjan", title: "زنجان", code: null, parent: 24 },
  { name: "Semnan", title: "سمنان", code: null, parent: 23 },
  {
    name: "SistanOBaluchestan",
    title: "سیستان و بلوچستان",
    code: null,
    parent: 54,
  },
  { name: "Fars", title: "فارس", code: null, parent: 71 },
  { name: "Qom", title: "قم", code: null, parent: 25 },
  { name: "Qazvin", title: "قزوین", code: null, parent: 28 },
  { name: "Kurdistan", title: "کردستان", code: null, parent: 87 },
  { name: "Kerman", title: "کرمان", code: null, parent: 34 },
  { name: "Kermanshah", title: "کرمانشاه", code: null, parent: 83 },
  {
    name: "KohgiluyehOBoyerAhmad",
    title: "کهکلویه و بویراحمد",
    code: null,
    parent: 74,
  },
  { name: "Golestan", title: "گلستان", code: null, parent: 17 },
  { name: "Gilan", title: "گیلان", code: null, parent: 13 },
  { name: "Lorestan", title: "لرستان", code: null, parent: 66 },
  { name: "Mazandaran", title: "مازندران", code: null, parent: 11 },
  { name: "Markazi", title: "مرکزی", code: null, parent: 86 },
  { name: "Hormozgan", title: "هرمزگان", code: null, parent: 76 },
  { name: "Hamedan", title: "همدان", code: null, parent: 81 },
  { name: "Yazd", title: "یزد", code: null, parent: 35 },
];
